/**
 * abra gen web api (spojení testapi)
 * webové api systému 17.03.03
 *
 * OpenAPI spec version: 17.03.03
 * Contact: abragen@abra.eu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package application.service.abra.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;


/**
 * Additionalcosts
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-03-29T11:52:08.096+02:00")
public class Additionalcosts   {
  @SerializedName("displayname")
  private String displayname = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("classid")
  private String classid = null;

  @SerializedName("objversion")
  private Integer objversion = null;

  @SerializedName("customsamount")
  private Double customsamount = null;

  @SerializedName("spendingtaxamount")
  private Double spendingtaxamount = null;

  @SerializedName("transportationamount")
  private Double transportationamount = null;

  @SerializedName("othercostamount")
  private Double othercostamount = null;

  @SerializedName("customstariff")
  private Double customstariff = null;

  @SerializedName("othercosttariff")
  private Double othercosttariff = null;

  @SerializedName("spendingtaxtariff")
  private Double spendingtaxtariff = null;

  @SerializedName("transportationtariff")
  private Double transportationtariff = null;

  @SerializedName("transportationused")
  private Boolean transportationused = null;

  @SerializedName("othercostused")
  private Boolean othercostused = null;

  @SerializedName("transportationislocal")
  private Boolean transportationislocal = null;

  @SerializedName("othercostislocal")
  private Boolean othercostislocal = null;

  @SerializedName("customsislocal")
  private Boolean customsislocal = null;

  @SerializedName("spendingtaxislocal")
  private Boolean spendingtaxislocal = null;

  @SerializedName("intrastataffectkind")
  private Integer intrastataffectkind = null;

  public Additionalcosts displayname(String displayname) {
    this.displayname = displayname;
    return this;
  }

   /**
   * název
   * @return displayname
  **/
  @ApiModelProperty(example = "null", value = "název")
  public String getDisplayname() {
    return displayname;
  }

  public void setDisplayname(String displayname) {
    this.displayname = displayname;
  }

  public Additionalcosts id(String id) {
    this.id = id;
    return this;
  }

   /**
   * vlastní id [persistentní položka]
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "vlastní id [persistentní položka]")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Additionalcosts classid(String classid) {
    this.classid = classid;
    return this;
  }

   /**
   * id třídy
   * @return classid
  **/
  @ApiModelProperty(example = "null", value = "id třídy")
  public String getClassid() {
    return classid;
  }

  public void setClassid(String classid) {
    this.classid = classid;
  }

  public Additionalcosts objversion(Integer objversion) {
    this.objversion = objversion;
    return this;
  }

   /**
   * verze objektu [persistentní položka]
   * @return objversion
  **/
  @ApiModelProperty(example = "null", value = "verze objektu [persistentní položka]")
  public Integer getObjversion() {
    return objversion;
  }

  public void setObjversion(Integer objversion) {
    this.objversion = objversion;
  }

  public Additionalcosts customsamount(Double customsamount) {
    this.customsamount = customsamount;
    return this;
  }

   /**
   * clo [persistentní položka]
   * @return customsamount
  **/
  @ApiModelProperty(example = "null", value = "clo [persistentní položka]")
  public Double getCustomsamount() {
    return customsamount;
  }

  public void setCustomsamount(Double customsamount) {
    this.customsamount = customsamount;
  }

  public Additionalcosts spendingtaxamount(Double spendingtaxamount) {
    this.spendingtaxamount = spendingtaxamount;
    return this;
  }

   /**
   * proc.náklady [persistentní položka]
   * @return spendingtaxamount
  **/
  @ApiModelProperty(example = "null", value = "proc.náklady [persistentní položka]")
  public Double getSpendingtaxamount() {
    return spendingtaxamount;
  }

  public void setSpendingtaxamount(Double spendingtaxamount) {
    this.spendingtaxamount = spendingtaxamount;
  }

  public Additionalcosts transportationamount(Double transportationamount) {
    this.transportationamount = transportationamount;
    return this;
  }

   /**
   * doprava [persistentní položka]
   * @return transportationamount
  **/
  @ApiModelProperty(example = "null", value = "doprava [persistentní položka]")
  public Double getTransportationamount() {
    return transportationamount;
  }

  public void setTransportationamount(Double transportationamount) {
    this.transportationamount = transportationamount;
  }

  public Additionalcosts othercostamount(Double othercostamount) {
    this.othercostamount = othercostamount;
    return this;
  }

   /**
   * ostatní náklady [persistentní položka]
   * @return othercostamount
  **/
  @ApiModelProperty(example = "null", value = "ostatní náklady [persistentní položka]")
  public Double getOthercostamount() {
    return othercostamount;
  }

  public void setOthercostamount(Double othercostamount) {
    this.othercostamount = othercostamount;
  }

  public Additionalcosts customstariff(Double customstariff) {
    this.customstariff = customstariff;
    return this;
  }

   /**
   * clo - sazba [persistentní položka]
   * @return customstariff
  **/
  @ApiModelProperty(example = "null", value = "clo - sazba [persistentní položka]")
  public Double getCustomstariff() {
    return customstariff;
  }

  public void setCustomstariff(Double customstariff) {
    this.customstariff = customstariff;
  }

  public Additionalcosts othercosttariff(Double othercosttariff) {
    this.othercosttariff = othercosttariff;
    return this;
  }

   /**
   * ost.nákl. - sazba [persistentní položka]
   * @return othercosttariff
  **/
  @ApiModelProperty(example = "null", value = "ost.nákl. - sazba [persistentní položka]")
  public Double getOthercosttariff() {
    return othercosttariff;
  }

  public void setOthercosttariff(Double othercosttariff) {
    this.othercosttariff = othercosttariff;
  }

  public Additionalcosts spendingtaxtariff(Double spendingtaxtariff) {
    this.spendingtaxtariff = spendingtaxtariff;
    return this;
  }

   /**
   * proc.náklady - sazba [persistentní položka]
   * @return spendingtaxtariff
  **/
  @ApiModelProperty(example = "null", value = "proc.náklady - sazba [persistentní položka]")
  public Double getSpendingtaxtariff() {
    return spendingtaxtariff;
  }

  public void setSpendingtaxtariff(Double spendingtaxtariff) {
    this.spendingtaxtariff = spendingtaxtariff;
  }

  public Additionalcosts transportationtariff(Double transportationtariff) {
    this.transportationtariff = transportationtariff;
    return this;
  }

   /**
   * doprava - sazba [persistentní položka]
   * @return transportationtariff
  **/
  @ApiModelProperty(example = "null", value = "doprava - sazba [persistentní položka]")
  public Double getTransportationtariff() {
    return transportationtariff;
  }

  public void setTransportationtariff(Double transportationtariff) {
    this.transportationtariff = transportationtariff;
  }

  public Additionalcosts transportationused(Boolean transportationused) {
    this.transportationused = transportationused;
    return this;
  }

   /**
   * je doprava [persistentní položka]
   * @return transportationused
  **/
  @ApiModelProperty(example = "null", value = "je doprava [persistentní položka]")
  public Boolean getTransportationused() {
    return transportationused;
  }

  public void setTransportationused(Boolean transportationused) {
    this.transportationused = transportationused;
  }

  public Additionalcosts othercostused(Boolean othercostused) {
    this.othercostused = othercostused;
    return this;
  }

   /**
   * jsou ostat.nákl. [persistentní položka]
   * @return othercostused
  **/
  @ApiModelProperty(example = "null", value = "jsou ostat.nákl. [persistentní položka]")
  public Boolean getOthercostused() {
    return othercostused;
  }

  public void setOthercostused(Boolean othercostused) {
    this.othercostused = othercostused;
  }

  public Additionalcosts transportationislocal(Boolean transportationislocal) {
    this.transportationislocal = transportationislocal;
    return this;
  }

   /**
   * dopr.lokál. [persistentní položka]
   * @return transportationislocal
  **/
  @ApiModelProperty(example = "null", value = "dopr.lokál. [persistentní položka]")
  public Boolean getTransportationislocal() {
    return transportationislocal;
  }

  public void setTransportationislocal(Boolean transportationislocal) {
    this.transportationislocal = transportationislocal;
  }

  public Additionalcosts othercostislocal(Boolean othercostislocal) {
    this.othercostislocal = othercostislocal;
    return this;
  }

   /**
   * ost.nákl.lokál. [persistentní položka]
   * @return othercostislocal
  **/
  @ApiModelProperty(example = "null", value = "ost.nákl.lokál. [persistentní položka]")
  public Boolean getOthercostislocal() {
    return othercostislocal;
  }

  public void setOthercostislocal(Boolean othercostislocal) {
    this.othercostislocal = othercostislocal;
  }

  public Additionalcosts customsislocal(Boolean customsislocal) {
    this.customsislocal = customsislocal;
    return this;
  }

   /**
   * clo lokálně [persistentní položka]
   * @return customsislocal
  **/
  @ApiModelProperty(example = "null", value = "clo lokálně [persistentní položka]")
  public Boolean getCustomsislocal() {
    return customsislocal;
  }

  public void setCustomsislocal(Boolean customsislocal) {
    this.customsislocal = customsislocal;
  }

  public Additionalcosts spendingtaxislocal(Boolean spendingtaxislocal) {
    this.spendingtaxislocal = spendingtaxislocal;
    return this;
  }

   /**
   * proc.náklady lokál. [persistentní položka]
   * @return spendingtaxislocal
  **/
  @ApiModelProperty(example = "null", value = "proc.náklady lokál. [persistentní položka]")
  public Boolean getSpendingtaxislocal() {
    return spendingtaxislocal;
  }

  public void setSpendingtaxislocal(Boolean spendingtaxislocal) {
    this.spendingtaxislocal = spendingtaxislocal;
  }

  public Additionalcosts intrastataffectkind(Integer intrastataffectkind) {
    this.intrastataffectkind = intrastataffectkind;
    return this;
  }

   /**
   * započítat do částky pro intrastat [persistentní položka]
   * @return intrastataffectkind
  **/
  @ApiModelProperty(example = "null", value = "započítat do částky pro intrastat [persistentní položka]")
  public Integer getIntrastataffectkind() {
    return intrastataffectkind;
  }

  public void setIntrastataffectkind(Integer intrastataffectkind) {
    this.intrastataffectkind = intrastataffectkind;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Additionalcosts additionalcosts = (Additionalcosts) o;
    return Objects.equals(this.displayname, additionalcosts.displayname) &&
        Objects.equals(this.id, additionalcosts.id) &&
        Objects.equals(this.classid, additionalcosts.classid) &&
        Objects.equals(this.objversion, additionalcosts.objversion) &&
        Objects.equals(this.customsamount, additionalcosts.customsamount) &&
        Objects.equals(this.spendingtaxamount, additionalcosts.spendingtaxamount) &&
        Objects.equals(this.transportationamount, additionalcosts.transportationamount) &&
        Objects.equals(this.othercostamount, additionalcosts.othercostamount) &&
        Objects.equals(this.customstariff, additionalcosts.customstariff) &&
        Objects.equals(this.othercosttariff, additionalcosts.othercosttariff) &&
        Objects.equals(this.spendingtaxtariff, additionalcosts.spendingtaxtariff) &&
        Objects.equals(this.transportationtariff, additionalcosts.transportationtariff) &&
        Objects.equals(this.transportationused, additionalcosts.transportationused) &&
        Objects.equals(this.othercostused, additionalcosts.othercostused) &&
        Objects.equals(this.transportationislocal, additionalcosts.transportationislocal) &&
        Objects.equals(this.othercostislocal, additionalcosts.othercostislocal) &&
        Objects.equals(this.customsislocal, additionalcosts.customsislocal) &&
        Objects.equals(this.spendingtaxislocal, additionalcosts.spendingtaxislocal) &&
        Objects.equals(this.intrastataffectkind, additionalcosts.intrastataffectkind);
  }

  @Override
  public int hashCode() {
    return Objects.hash(displayname, id, classid, objversion, customsamount, spendingtaxamount, transportationamount, othercostamount, customstariff, othercosttariff, spendingtaxtariff, transportationtariff, transportationused, othercostused, transportationislocal, othercostislocal, customsislocal, spendingtaxislocal, intrastataffectkind);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Additionalcosts {\n");
    
    sb.append("    displayname: ").append(toIndentedString(displayname)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    classid: ").append(toIndentedString(classid)).append("\n");
    sb.append("    objversion: ").append(toIndentedString(objversion)).append("\n");
    sb.append("    customsamount: ").append(toIndentedString(customsamount)).append("\n");
    sb.append("    spendingtaxamount: ").append(toIndentedString(spendingtaxamount)).append("\n");
    sb.append("    transportationamount: ").append(toIndentedString(transportationamount)).append("\n");
    sb.append("    othercostamount: ").append(toIndentedString(othercostamount)).append("\n");
    sb.append("    customstariff: ").append(toIndentedString(customstariff)).append("\n");
    sb.append("    othercosttariff: ").append(toIndentedString(othercosttariff)).append("\n");
    sb.append("    spendingtaxtariff: ").append(toIndentedString(spendingtaxtariff)).append("\n");
    sb.append("    transportationtariff: ").append(toIndentedString(transportationtariff)).append("\n");
    sb.append("    transportationused: ").append(toIndentedString(transportationused)).append("\n");
    sb.append("    othercostused: ").append(toIndentedString(othercostused)).append("\n");
    sb.append("    transportationislocal: ").append(toIndentedString(transportationislocal)).append("\n");
    sb.append("    othercostislocal: ").append(toIndentedString(othercostislocal)).append("\n");
    sb.append("    customsislocal: ").append(toIndentedString(customsislocal)).append("\n");
    sb.append("    spendingtaxislocal: ").append(toIndentedString(spendingtaxislocal)).append("\n");
    sb.append("    intrastataffectkind: ").append(toIndentedString(intrastataffectkind)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

