/**
 * abra gen web api (spojení testapi)
 * webové api systému 17.03.03
 *
 * OpenAPI spec version: 17.03.03
 * Contact: abragen@abra.eu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package application.service.abra.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


/**
 * Bankaccount
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-03-29T11:52:08.096+02:00")
public class Bankaccount   {
  @SerializedName("displayname")
  private String displayname = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("classid")
  private String classid = null;

  @SerializedName("objversion")
  private Integer objversion = null;

  @SerializedName("rows")
  private List<Bankaccountbeginning> rows = new ArrayList<Bankaccountbeginning>();

  @SerializedName("hidden")
  private Boolean hidden = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("bankaccount")
  private String bankaccount = null;

  @SerializedName("specsymbol")
  private String specsymbol = null;

  @SerializedName("bankstatement_id")
  private String bankstatementId = null;

  @SerializedName("paymentorder_id")
  private String paymentorderId = null;

  @SerializedName("account_id")
  private String accountId = null;

  @SerializedName("division_id")
  private String divisionId = null;

  @SerializedName("firstopenperiod_id")
  private String firstopenperiodId = null;

  @SerializedName("lastopenperiod_id")
  private String lastopenperiodId = null;

  @SerializedName("firstlocalamount")
  private Double firstlocalamount = null;

  @SerializedName("firstamount")
  private Double firstamount = null;

  @SerializedName("currency_id")
  private String currencyId = null;

  @SerializedName("swiftcode")
  private String swiftcode = null;

  @SerializedName("ibancode")
  private String ibancode = null;

  @SerializedName("bankcountry_id")
  private String bankcountryId = null;

  public Bankaccount displayname(String displayname) {
    this.displayname = displayname;
    return this;
  }

   /**
   * název
   * @return displayname
  **/
  @ApiModelProperty(example = "null", value = "název")
  public String getDisplayname() {
    return displayname;
  }

  public void setDisplayname(String displayname) {
    this.displayname = displayname;
  }

  public Bankaccount id(String id) {
    this.id = id;
    return this;
  }

   /**
   * vlastní id [persistentní položka]
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "vlastní id [persistentní položka]")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Bankaccount classid(String classid) {
    this.classid = classid;
    return this;
  }

   /**
   * id třídy
   * @return classid
  **/
  @ApiModelProperty(example = "null", value = "id třídy")
  public String getClassid() {
    return classid;
  }

  public void setClassid(String classid) {
    this.classid = classid;
  }

  public Bankaccount objversion(Integer objversion) {
    this.objversion = objversion;
    return this;
  }

   /**
   * verze objektu [persistentní položka]
   * @return objversion
  **/
  @ApiModelProperty(example = "null", value = "verze objektu [persistentní položka]")
  public Integer getObjversion() {
    return objversion;
  }

  public void setObjversion(Integer objversion) {
    this.objversion = objversion;
  }

  public Bankaccount rows(List<Bankaccountbeginning> rows) {
    this.rows = rows;
    return this;
  }

  public Bankaccount addRowsItem(Bankaccountbeginning rowsItem) {
    this.rows.add(rowsItem);
    return this;
  }

   /**
   * počátky; kolekce bo počátek bankovního účtu [nepersistentní položka]
   * @return rows
  **/
  @ApiModelProperty(example = "null", value = "počátky; kolekce bo počátek bankovního účtu [nepersistentní položka]")
  public List<Bankaccountbeginning> getRows() {
    return rows;
  }

  public void setRows(List<Bankaccountbeginning> rows) {
    this.rows = rows;
  }

  public Bankaccount hidden(Boolean hidden) {
    this.hidden = hidden;
    return this;
  }

   /**
   * skrytý [persistentní položka]
   * @return hidden
  **/
  @ApiModelProperty(example = "null", value = "skrytý [persistentní položka]")
  public Boolean getHidden() {
    return hidden;
  }

  public void setHidden(Boolean hidden) {
    this.hidden = hidden;
  }

  public Bankaccount name(String name) {
    this.name = name;
    return this;
  }

   /**
   * název [persistentní položka]
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "název [persistentní položka]")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Bankaccount bankaccount(String bankaccount) {
    this.bankaccount = bankaccount;
    return this;
  }

   /**
   * bank.účet [persistentní položka]
   * @return bankaccount
  **/
  @ApiModelProperty(example = "null", value = "bank.účet [persistentní položka]")
  public String getBankaccount() {
    return bankaccount;
  }

  public void setBankaccount(String bankaccount) {
    this.bankaccount = bankaccount;
  }

  public Bankaccount specsymbol(String specsymbol) {
    this.specsymbol = specsymbol;
    return this;
  }

   /**
   * spec.symbol [persistentní položka]
   * @return specsymbol
  **/
  @ApiModelProperty(example = "null", value = "spec.symbol [persistentní položka]")
  public String getSpecsymbol() {
    return specsymbol;
  }

  public void setSpecsymbol(String specsymbol) {
    this.specsymbol = specsymbol;
  }

  public Bankaccount bankstatementId(String bankstatementId) {
    this.bankstatementId = bankstatementId;
    return this;
  }

   /**
   * bankovní výpis; id objektu Řada dokladů [persistentní položka]
   * @return bankstatementId
  **/
  @ApiModelProperty(example = "null", value = "bankovní výpis; id objektu Řada dokladů [persistentní položka]")
  public String getBankstatementId() {
    return bankstatementId;
  }

  public void setBankstatementId(String bankstatementId) {
    this.bankstatementId = bankstatementId;
  }

  public Bankaccount paymentorderId(String paymentorderId) {
    this.paymentorderId = paymentorderId;
    return this;
  }

   /**
   * platební příkaz; id objektu Řada dokladů [persistentní položka]
   * @return paymentorderId
  **/
  @ApiModelProperty(example = "null", value = "platební příkaz; id objektu Řada dokladů [persistentní položka]")
  public String getPaymentorderId() {
    return paymentorderId;
  }

  public void setPaymentorderId(String paymentorderId) {
    this.paymentorderId = paymentorderId;
  }

  public Bankaccount accountId(String accountId) {
    this.accountId = accountId;
    return this;
  }

   /**
   * Účet; id objektu Účet účetního rozvrhu [persistentní položka]
   * @return accountId
  **/
  @ApiModelProperty(example = "null", value = "Účet; id objektu Účet účetního rozvrhu [persistentní položka]")
  public String getAccountId() {
    return accountId;
  }

  public void setAccountId(String accountId) {
    this.accountId = accountId;
  }

  public Bankaccount divisionId(String divisionId) {
    this.divisionId = divisionId;
    return this;
  }

   /**
   * středisko; id objektu středisko [persistentní položka]
   * @return divisionId
  **/
  @ApiModelProperty(example = "null", value = "středisko; id objektu středisko [persistentní položka]")
  public String getDivisionId() {
    return divisionId;
  }

  public void setDivisionId(String divisionId) {
    this.divisionId = divisionId;
  }

  public Bankaccount firstopenperiodId(String firstopenperiodId) {
    this.firstopenperiodId = firstopenperiodId;
    return this;
  }

   /**
   * první období; id objektu období [persistentní položka]
   * @return firstopenperiodId
  **/
  @ApiModelProperty(example = "null", value = "první období; id objektu období [persistentní položka]")
  public String getFirstopenperiodId() {
    return firstopenperiodId;
  }

  public void setFirstopenperiodId(String firstopenperiodId) {
    this.firstopenperiodId = firstopenperiodId;
  }

  public Bankaccount lastopenperiodId(String lastopenperiodId) {
    this.lastopenperiodId = lastopenperiodId;
    return this;
  }

   /**
   * akt.období; id objektu období [persistentní položka]
   * @return lastopenperiodId
  **/
  @ApiModelProperty(example = "null", value = "akt.období; id objektu období [persistentní položka]")
  public String getLastopenperiodId() {
    return lastopenperiodId;
  }

  public void setLastopenperiodId(String lastopenperiodId) {
    this.lastopenperiodId = lastopenperiodId;
  }

  public Bankaccount firstlocalamount(Double firstlocalamount) {
    this.firstlocalamount = firstlocalamount;
    return this;
  }

   /**
   * lokál.částka prvního poč.
   * @return firstlocalamount
  **/
  @ApiModelProperty(example = "null", value = "lokál.částka prvního poč.")
  public Double getFirstlocalamount() {
    return firstlocalamount;
  }

  public void setFirstlocalamount(Double firstlocalamount) {
    this.firstlocalamount = firstlocalamount;
  }

  public Bankaccount firstamount(Double firstamount) {
    this.firstamount = firstamount;
    return this;
  }

   /**
   * Částka prvního poč.
   * @return firstamount
  **/
  @ApiModelProperty(example = "null", value = "Částka prvního poč.")
  public Double getFirstamount() {
    return firstamount;
  }

  public void setFirstamount(Double firstamount) {
    this.firstamount = firstamount;
  }

  public Bankaccount currencyId(String currencyId) {
    this.currencyId = currencyId;
    return this;
  }

   /**
   * měna; id objektu měna [persistentní položka]
   * @return currencyId
  **/
  @ApiModelProperty(example = "null", value = "měna; id objektu měna [persistentní položka]")
  public String getCurrencyId() {
    return currencyId;
  }

  public void setCurrencyId(String currencyId) {
    this.currencyId = currencyId;
  }

  public Bankaccount swiftcode(String swiftcode) {
    this.swiftcode = swiftcode;
    return this;
  }

   /**
   * swift [persistentní položka]
   * @return swiftcode
  **/
  @ApiModelProperty(example = "null", value = "swift [persistentní položka]")
  public String getSwiftcode() {
    return swiftcode;
  }

  public void setSwiftcode(String swiftcode) {
    this.swiftcode = swiftcode;
  }

  public Bankaccount ibancode(String ibancode) {
    this.ibancode = ibancode;
    return this;
  }

   /**
   * iban [persistentní položka]
   * @return ibancode
  **/
  @ApiModelProperty(example = "null", value = "iban [persistentní položka]")
  public String getIbancode() {
    return ibancode;
  }

  public void setIbancode(String ibancode) {
    this.ibancode = ibancode;
  }

  public Bankaccount bankcountryId(String bankcountryId) {
    this.bankcountryId = bankcountryId;
    return this;
  }

   /**
   * země banky; id objektu země [persistentní položka]
   * @return bankcountryId
  **/
  @ApiModelProperty(example = "null", value = "země banky; id objektu země [persistentní položka]")
  public String getBankcountryId() {
    return bankcountryId;
  }

  public void setBankcountryId(String bankcountryId) {
    this.bankcountryId = bankcountryId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Bankaccount bankaccount = (Bankaccount) o;
    return Objects.equals(this.displayname, bankaccount.displayname) &&
        Objects.equals(this.id, bankaccount.id) &&
        Objects.equals(this.classid, bankaccount.classid) &&
        Objects.equals(this.objversion, bankaccount.objversion) &&
        Objects.equals(this.rows, bankaccount.rows) &&
        Objects.equals(this.hidden, bankaccount.hidden) &&
        Objects.equals(this.name, bankaccount.name) &&
        Objects.equals(this.bankaccount, bankaccount.bankaccount) &&
        Objects.equals(this.specsymbol, bankaccount.specsymbol) &&
        Objects.equals(this.bankstatementId, bankaccount.bankstatementId) &&
        Objects.equals(this.paymentorderId, bankaccount.paymentorderId) &&
        Objects.equals(this.accountId, bankaccount.accountId) &&
        Objects.equals(this.divisionId, bankaccount.divisionId) &&
        Objects.equals(this.firstopenperiodId, bankaccount.firstopenperiodId) &&
        Objects.equals(this.lastopenperiodId, bankaccount.lastopenperiodId) &&
        Objects.equals(this.firstlocalamount, bankaccount.firstlocalamount) &&
        Objects.equals(this.firstamount, bankaccount.firstamount) &&
        Objects.equals(this.currencyId, bankaccount.currencyId) &&
        Objects.equals(this.swiftcode, bankaccount.swiftcode) &&
        Objects.equals(this.ibancode, bankaccount.ibancode) &&
        Objects.equals(this.bankcountryId, bankaccount.bankcountryId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(displayname, id, classid, objversion, rows, hidden, name, bankaccount, specsymbol, bankstatementId, paymentorderId, accountId, divisionId, firstopenperiodId, lastopenperiodId, firstlocalamount, firstamount, currencyId, swiftcode, ibancode, bankcountryId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Bankaccount {\n");
    
    sb.append("    displayname: ").append(toIndentedString(displayname)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    classid: ").append(toIndentedString(classid)).append("\n");
    sb.append("    objversion: ").append(toIndentedString(objversion)).append("\n");
    sb.append("    rows: ").append(toIndentedString(rows)).append("\n");
    sb.append("    hidden: ").append(toIndentedString(hidden)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    bankaccount: ").append(toIndentedString(bankaccount)).append("\n");
    sb.append("    specsymbol: ").append(toIndentedString(specsymbol)).append("\n");
    sb.append("    bankstatementId: ").append(toIndentedString(bankstatementId)).append("\n");
    sb.append("    paymentorderId: ").append(toIndentedString(paymentorderId)).append("\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    divisionId: ").append(toIndentedString(divisionId)).append("\n");
    sb.append("    firstopenperiodId: ").append(toIndentedString(firstopenperiodId)).append("\n");
    sb.append("    lastopenperiodId: ").append(toIndentedString(lastopenperiodId)).append("\n");
    sb.append("    firstlocalamount: ").append(toIndentedString(firstlocalamount)).append("\n");
    sb.append("    firstamount: ").append(toIndentedString(firstamount)).append("\n");
    sb.append("    currencyId: ").append(toIndentedString(currencyId)).append("\n");
    sb.append("    swiftcode: ").append(toIndentedString(swiftcode)).append("\n");
    sb.append("    ibancode: ").append(toIndentedString(ibancode)).append("\n");
    sb.append("    bankcountryId: ").append(toIndentedString(bankcountryId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

