/**
 * abra gen web api (spojení testapi)
 * webové api systému 17.03.03
 *
 * OpenAPI spec version: 17.03.03
 * Contact: abragen@abra.eu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package application.service.abra.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;

import java.util.Objects;


/**
 * Bookentry
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-03-29T11:52:08.096+02:00")
public class Bookentry   {
  @SerializedName("displayname")
  private String displayname = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("classid")
  private String classid = null;

  @SerializedName("objversion")
  private Integer objversion = null;

  @SerializedName("accdate$date")
  private DateTime accdatedate = null;

  @SerializedName("accdocqueue_id")
  private String accdocqueueId = null;

  @SerializedName("period_id")
  private String periodId = null;

  @SerializedName("ordnumber")
  private Integer ordnumber = null;

  @SerializedName("firm_id")
  private String firmId = null;

  @SerializedName("createdby_id")
  private String createdbyId = null;

  @SerializedName("correctedby_id")
  private String correctedbyId = null;

  @SerializedName("text")
  private String text = null;

  @SerializedName("amount")
  private Double amount = null;

  @SerializedName("currency_id")
  private String currencyId = null;

  @SerializedName("amountincurrency")
  private Double amountincurrency = null;

  @SerializedName("audited")
  private Boolean audited = null;

  @SerializedName("accgroup_id")
  private String accgroupId = null;

  @SerializedName("isrequest")
  private Boolean isrequest = null;

  @SerializedName("debitaccount_id")
  private String debitaccountId = null;

  @SerializedName("debitdivision_id")
  private String debitdivisionId = null;

  @SerializedName("debitbusorder_id")
  private String debitbusorderId = null;

  @SerializedName("debitbustransaction_id")
  private String debitbustransactionId = null;

  @SerializedName("debitbusproject_id")
  private String debitbusprojectId = null;

  @SerializedName("creditaccount_id")
  private String creditaccountId = null;

  @SerializedName("creditdivision_id")
  private String creditdivisionId = null;

  @SerializedName("creditbusorder_id")
  private String creditbusorderId = null;

  @SerializedName("creditbustransaction_id")
  private String creditbustransactionId = null;

  @SerializedName("creditbusproject_id")
  private String creditbusprojectId = null;

  @SerializedName("groupfirm_id")
  private String groupfirmId = null;

  public Bookentry displayname(String displayname) {
    this.displayname = displayname;
    return this;
  }

   /**
   * Číslo dok.
   * @return displayname
  **/
  @ApiModelProperty(example = "null", value = "Číslo dok.")
  public String getDisplayname() {
    return displayname;
  }

  public void setDisplayname(String displayname) {
    this.displayname = displayname;
  }

  public Bookentry id(String id) {
    this.id = id;
    return this;
  }

   /**
   * vlastní id [persistentní položka]
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "vlastní id [persistentní položka]")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Bookentry classid(String classid) {
    this.classid = classid;
    return this;
  }

   /**
   * id třídy
   * @return classid
  **/
  @ApiModelProperty(example = "null", value = "id třídy")
  public String getClassid() {
    return classid;
  }

  public void setClassid(String classid) {
    this.classid = classid;
  }

  public Bookentry objversion(Integer objversion) {
    this.objversion = objversion;
    return this;
  }

   /**
   * verze objektu [persistentní položka]
   * @return objversion
  **/
  @ApiModelProperty(example = "null", value = "verze objektu [persistentní položka]")
  public Integer getObjversion() {
    return objversion;
  }

  public void setObjversion(Integer objversion) {
    this.objversion = objversion;
  }

  public Bookentry accdatedate(DateTime accdatedate) {
    this.accdatedate = accdatedate;
    return this;
  }

   /**
   * datum účtování [persistentní položka]
   * @return accdatedate
  **/
  @ApiModelProperty(example = "null", value = "datum účtování [persistentní položka]")
  public DateTime getAccdatedate() {
    return accdatedate;
  }

  public void setAccdatedate(DateTime accdatedate) {
    this.accdatedate = accdatedate;
  }

  public Bookentry accdocqueueId(String accdocqueueId) {
    this.accdocqueueId = accdocqueueId;
    return this;
  }

   /**
   * Účetní řada; id objektu Účetní řada dokladů [persistentní položka]
   * @return accdocqueueId
  **/
  @ApiModelProperty(example = "null", value = "Účetní řada; id objektu Účetní řada dokladů [persistentní položka]")
  public String getAccdocqueueId() {
    return accdocqueueId;
  }

  public void setAccdocqueueId(String accdocqueueId) {
    this.accdocqueueId = accdocqueueId;
  }

  public Bookentry periodId(String periodId) {
    this.periodId = periodId;
    return this;
  }

   /**
   * období; id objektu období [persistentní položka]
   * @return periodId
  **/
  @ApiModelProperty(example = "null", value = "období; id objektu období [persistentní položka]")
  public String getPeriodId() {
    return periodId;
  }

  public void setPeriodId(String periodId) {
    this.periodId = periodId;
  }

  public Bookentry ordnumber(Integer ordnumber) {
    this.ordnumber = ordnumber;
    return this;
  }

   /**
   * pořadové číslo [persistentní položka]
   * @return ordnumber
  **/
  @ApiModelProperty(example = "null", value = "pořadové číslo [persistentní položka]")
  public Integer getOrdnumber() {
    return ordnumber;
  }

  public void setOrdnumber(Integer ordnumber) {
    this.ordnumber = ordnumber;
  }

  public Bookentry firmId(String firmId) {
    this.firmId = firmId;
    return this;
  }

   /**
   * firma; id objektu firma [persistentní položka]
   * @return firmId
  **/
  @ApiModelProperty(example = "null", value = "firma; id objektu firma [persistentní položka]")
  public String getFirmId() {
    return firmId;
  }

  public void setFirmId(String firmId) {
    this.firmId = firmId;
  }

  public Bookentry createdbyId(String createdbyId) {
    this.createdbyId = createdbyId;
    return this;
  }

   /**
   * vytvořil; id objektu uživatel [persistentní položka]
   * @return createdbyId
  **/
  @ApiModelProperty(example = "null", value = "vytvořil; id objektu uživatel [persistentní položka]")
  public String getCreatedbyId() {
    return createdbyId;
  }

  public void setCreatedbyId(String createdbyId) {
    this.createdbyId = createdbyId;
  }

  public Bookentry correctedbyId(String correctedbyId) {
    this.correctedbyId = correctedbyId;
    return this;
  }

   /**
   * opravil; id objektu uživatel [persistentní položka]
   * @return correctedbyId
  **/
  @ApiModelProperty(example = "null", value = "opravil; id objektu uživatel [persistentní položka]")
  public String getCorrectedbyId() {
    return correctedbyId;
  }

  public void setCorrectedbyId(String correctedbyId) {
    this.correctedbyId = correctedbyId;
  }

  public Bookentry text(String text) {
    this.text = text;
    return this;
  }

   /**
   * text [persistentní položka]
   * @return text
  **/
  @ApiModelProperty(example = "null", value = "text [persistentní položka]")
  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }

  public Bookentry amount(Double amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Částka [persistentní položka]
   * @return amount
  **/
  @ApiModelProperty(example = "null", value = "Částka [persistentní položka]")
  public Double getAmount() {
    return amount;
  }

  public void setAmount(Double amount) {
    this.amount = amount;
  }

  public Bookentry currencyId(String currencyId) {
    this.currencyId = currencyId;
    return this;
  }

   /**
   * měna; id objektu měna [persistentní položka]
   * @return currencyId
  **/
  @ApiModelProperty(example = "null", value = "měna; id objektu měna [persistentní položka]")
  public String getCurrencyId() {
    return currencyId;
  }

  public void setCurrencyId(String currencyId) {
    this.currencyId = currencyId;
  }

  public Bookentry amountincurrency(Double amountincurrency) {
    this.amountincurrency = amountincurrency;
    return this;
  }

   /**
   * cizí částka [persistentní položka]
   * @return amountincurrency
  **/
  @ApiModelProperty(example = "null", value = "cizí částka [persistentní položka]")
  public Double getAmountincurrency() {
    return amountincurrency;
  }

  public void setAmountincurrency(Double amountincurrency) {
    this.amountincurrency = amountincurrency;
  }

  public Bookentry audited(Boolean audited) {
    this.audited = audited;
    return this;
  }

   /**
   * audit [persistentní položka]
   * @return audited
  **/
  @ApiModelProperty(example = "null", value = "audit [persistentní položka]")
  public Boolean getAudited() {
    return audited;
  }

  public void setAudited(Boolean audited) {
    this.audited = audited;
  }

  public Bookentry accgroupId(String accgroupId) {
    this.accgroupId = accgroupId;
    return this;
  }

   /**
   * Účetní skupina; id objektu Účetní skupina [persistentní položka]
   * @return accgroupId
  **/
  @ApiModelProperty(example = "null", value = "Účetní skupina; id objektu Účetní skupina [persistentní položka]")
  public String getAccgroupId() {
    return accgroupId;
  }

  public void setAccgroupId(String accgroupId) {
    this.accgroupId = accgroupId;
  }

  public Bookentry isrequest(Boolean isrequest) {
    this.isrequest = isrequest;
    return this;
  }

   /**
   * Žádost [persistentní položka]
   * @return isrequest
  **/
  @ApiModelProperty(example = "null", value = "Žádost [persistentní položka]")
  public Boolean getIsrequest() {
    return isrequest;
  }

  public void setIsrequest(Boolean isrequest) {
    this.isrequest = isrequest;
  }

  public Bookentry debitaccountId(String debitaccountId) {
    this.debitaccountId = debitaccountId;
    return this;
  }

   /**
   * Účet md; id objektu Účet účetního rozvrhu [persistentní položka]
   * @return debitaccountId
  **/
  @ApiModelProperty(example = "null", value = "Účet md; id objektu Účet účetního rozvrhu [persistentní položka]")
  public String getDebitaccountId() {
    return debitaccountId;
  }

  public void setDebitaccountId(String debitaccountId) {
    this.debitaccountId = debitaccountId;
  }

  public Bookentry debitdivisionId(String debitdivisionId) {
    this.debitdivisionId = debitdivisionId;
    return this;
  }

   /**
   * středisko md; id objektu středisko [persistentní položka]
   * @return debitdivisionId
  **/
  @ApiModelProperty(example = "null", value = "středisko md; id objektu středisko [persistentní položka]")
  public String getDebitdivisionId() {
    return debitdivisionId;
  }

  public void setDebitdivisionId(String debitdivisionId) {
    this.debitdivisionId = debitdivisionId;
  }

  public Bookentry debitbusorderId(String debitbusorderId) {
    this.debitbusorderId = debitbusorderId;
    return this;
  }

   /**
   * zakázka md; id objektu zakázka [persistentní položka]
   * @return debitbusorderId
  **/
  @ApiModelProperty(example = "null", value = "zakázka md; id objektu zakázka [persistentní položka]")
  public String getDebitbusorderId() {
    return debitbusorderId;
  }

  public void setDebitbusorderId(String debitbusorderId) {
    this.debitbusorderId = debitbusorderId;
  }

  public Bookentry debitbustransactionId(String debitbustransactionId) {
    this.debitbustransactionId = debitbustransactionId;
    return this;
  }

   /**
   * o.případ md; id objektu obchodní případ [persistentní položka]
   * @return debitbustransactionId
  **/
  @ApiModelProperty(example = "null", value = "o.případ md; id objektu obchodní případ [persistentní položka]")
  public String getDebitbustransactionId() {
    return debitbustransactionId;
  }

  public void setDebitbustransactionId(String debitbustransactionId) {
    this.debitbustransactionId = debitbustransactionId;
  }

  public Bookentry debitbusprojectId(String debitbusprojectId) {
    this.debitbusprojectId = debitbusprojectId;
    return this;
  }

   /**
   * projekt md; id objektu projekt [persistentní položka]
   * @return debitbusprojectId
  **/
  @ApiModelProperty(example = "null", value = "projekt md; id objektu projekt [persistentní položka]")
  public String getDebitbusprojectId() {
    return debitbusprojectId;
  }

  public void setDebitbusprojectId(String debitbusprojectId) {
    this.debitbusprojectId = debitbusprojectId;
  }

  public Bookentry creditaccountId(String creditaccountId) {
    this.creditaccountId = creditaccountId;
    return this;
  }

   /**
   * Účet d; id objektu Účet účetního rozvrhu [persistentní položka]
   * @return creditaccountId
  **/
  @ApiModelProperty(example = "null", value = "Účet d; id objektu Účet účetního rozvrhu [persistentní položka]")
  public String getCreditaccountId() {
    return creditaccountId;
  }

  public void setCreditaccountId(String creditaccountId) {
    this.creditaccountId = creditaccountId;
  }

  public Bookentry creditdivisionId(String creditdivisionId) {
    this.creditdivisionId = creditdivisionId;
    return this;
  }

   /**
   * středisko d; id objektu středisko [persistentní položka]
   * @return creditdivisionId
  **/
  @ApiModelProperty(example = "null", value = "středisko d; id objektu středisko [persistentní položka]")
  public String getCreditdivisionId() {
    return creditdivisionId;
  }

  public void setCreditdivisionId(String creditdivisionId) {
    this.creditdivisionId = creditdivisionId;
  }

  public Bookentry creditbusorderId(String creditbusorderId) {
    this.creditbusorderId = creditbusorderId;
    return this;
  }

   /**
   * zakázka d; id objektu zakázka [persistentní položka]
   * @return creditbusorderId
  **/
  @ApiModelProperty(example = "null", value = "zakázka d; id objektu zakázka [persistentní položka]")
  public String getCreditbusorderId() {
    return creditbusorderId;
  }

  public void setCreditbusorderId(String creditbusorderId) {
    this.creditbusorderId = creditbusorderId;
  }

  public Bookentry creditbustransactionId(String creditbustransactionId) {
    this.creditbustransactionId = creditbustransactionId;
    return this;
  }

   /**
   * o.případ d; id objektu obchodní případ [persistentní položka]
   * @return creditbustransactionId
  **/
  @ApiModelProperty(example = "null", value = "o.případ d; id objektu obchodní případ [persistentní položka]")
  public String getCreditbustransactionId() {
    return creditbustransactionId;
  }

  public void setCreditbustransactionId(String creditbustransactionId) {
    this.creditbustransactionId = creditbustransactionId;
  }

  public Bookentry creditbusprojectId(String creditbusprojectId) {
    this.creditbusprojectId = creditbusprojectId;
    return this;
  }

   /**
   * projekt d; id objektu projekt [persistentní položka]
   * @return creditbusprojectId
  **/
  @ApiModelProperty(example = "null", value = "projekt d; id objektu projekt [persistentní položka]")
  public String getCreditbusprojectId() {
    return creditbusprojectId;
  }

  public void setCreditbusprojectId(String creditbusprojectId) {
    this.creditbusprojectId = creditbusprojectId;
  }

  public Bookentry groupfirmId(String groupfirmId) {
    this.groupfirmId = groupfirmId;
    return this;
  }

   /**
   * firma pro skupinu; id objektu firma
   * @return groupfirmId
  **/
  @ApiModelProperty(example = "null", value = "firma pro skupinu; id objektu firma")
  public String getGroupfirmId() {
    return groupfirmId;
  }

  public void setGroupfirmId(String groupfirmId) {
    this.groupfirmId = groupfirmId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Bookentry bookentry = (Bookentry) o;
    return Objects.equals(this.displayname, bookentry.displayname) &&
        Objects.equals(this.id, bookentry.id) &&
        Objects.equals(this.classid, bookentry.classid) &&
        Objects.equals(this.objversion, bookentry.objversion) &&
        Objects.equals(this.accdatedate, bookentry.accdatedate) &&
        Objects.equals(this.accdocqueueId, bookentry.accdocqueueId) &&
        Objects.equals(this.periodId, bookentry.periodId) &&
        Objects.equals(this.ordnumber, bookentry.ordnumber) &&
        Objects.equals(this.firmId, bookentry.firmId) &&
        Objects.equals(this.createdbyId, bookentry.createdbyId) &&
        Objects.equals(this.correctedbyId, bookentry.correctedbyId) &&
        Objects.equals(this.text, bookentry.text) &&
        Objects.equals(this.amount, bookentry.amount) &&
        Objects.equals(this.currencyId, bookentry.currencyId) &&
        Objects.equals(this.amountincurrency, bookentry.amountincurrency) &&
        Objects.equals(this.audited, bookentry.audited) &&
        Objects.equals(this.accgroupId, bookentry.accgroupId) &&
        Objects.equals(this.isrequest, bookentry.isrequest) &&
        Objects.equals(this.debitaccountId, bookentry.debitaccountId) &&
        Objects.equals(this.debitdivisionId, bookentry.debitdivisionId) &&
        Objects.equals(this.debitbusorderId, bookentry.debitbusorderId) &&
        Objects.equals(this.debitbustransactionId, bookentry.debitbustransactionId) &&
        Objects.equals(this.debitbusprojectId, bookentry.debitbusprojectId) &&
        Objects.equals(this.creditaccountId, bookentry.creditaccountId) &&
        Objects.equals(this.creditdivisionId, bookentry.creditdivisionId) &&
        Objects.equals(this.creditbusorderId, bookentry.creditbusorderId) &&
        Objects.equals(this.creditbustransactionId, bookentry.creditbustransactionId) &&
        Objects.equals(this.creditbusprojectId, bookentry.creditbusprojectId) &&
        Objects.equals(this.groupfirmId, bookentry.groupfirmId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(displayname, id, classid, objversion, accdatedate, accdocqueueId, periodId, ordnumber, firmId, createdbyId, correctedbyId, text, amount, currencyId, amountincurrency, audited, accgroupId, isrequest, debitaccountId, debitdivisionId, debitbusorderId, debitbustransactionId, debitbusprojectId, creditaccountId, creditdivisionId, creditbusorderId, creditbustransactionId, creditbusprojectId, groupfirmId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Bookentry {\n");
    
    sb.append("    displayname: ").append(toIndentedString(displayname)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    classid: ").append(toIndentedString(classid)).append("\n");
    sb.append("    objversion: ").append(toIndentedString(objversion)).append("\n");
    sb.append("    accdatedate: ").append(toIndentedString(accdatedate)).append("\n");
    sb.append("    accdocqueueId: ").append(toIndentedString(accdocqueueId)).append("\n");
    sb.append("    periodId: ").append(toIndentedString(periodId)).append("\n");
    sb.append("    ordnumber: ").append(toIndentedString(ordnumber)).append("\n");
    sb.append("    firmId: ").append(toIndentedString(firmId)).append("\n");
    sb.append("    createdbyId: ").append(toIndentedString(createdbyId)).append("\n");
    sb.append("    correctedbyId: ").append(toIndentedString(correctedbyId)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    currencyId: ").append(toIndentedString(currencyId)).append("\n");
    sb.append("    amountincurrency: ").append(toIndentedString(amountincurrency)).append("\n");
    sb.append("    audited: ").append(toIndentedString(audited)).append("\n");
    sb.append("    accgroupId: ").append(toIndentedString(accgroupId)).append("\n");
    sb.append("    isrequest: ").append(toIndentedString(isrequest)).append("\n");
    sb.append("    debitaccountId: ").append(toIndentedString(debitaccountId)).append("\n");
    sb.append("    debitdivisionId: ").append(toIndentedString(debitdivisionId)).append("\n");
    sb.append("    debitbusorderId: ").append(toIndentedString(debitbusorderId)).append("\n");
    sb.append("    debitbustransactionId: ").append(toIndentedString(debitbustransactionId)).append("\n");
    sb.append("    debitbusprojectId: ").append(toIndentedString(debitbusprojectId)).append("\n");
    sb.append("    creditaccountId: ").append(toIndentedString(creditaccountId)).append("\n");
    sb.append("    creditdivisionId: ").append(toIndentedString(creditdivisionId)).append("\n");
    sb.append("    creditbusorderId: ").append(toIndentedString(creditbusorderId)).append("\n");
    sb.append("    creditbustransactionId: ").append(toIndentedString(creditbustransactionId)).append("\n");
    sb.append("    creditbusprojectId: ").append(toIndentedString(creditbusprojectId)).append("\n");
    sb.append("    groupfirmId: ").append(toIndentedString(groupfirmId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

