/**
 * ABRA Gen Web API (spojení testapi)
 * Webové API systému 17.03.03
 *
 * OpenAPI spec version: 17.03.03
 * Contact: abragen@abra.eu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package application.service.abra.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;

import java.util.Objects;


/**
 * Documentparticipant
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-03-26T20:30:15.152+02:00")
public class Documentparticipant   {
  @SerializedName("DisplayName")
  private String displayName = null;

  @SerializedName("ID")
  private String ID = null;

  @SerializedName("ClassID")
  private String classID = null;

  @SerializedName("ObjVersion")
  private Integer objVersion = null;

  @SerializedName("Revided_ID")
  private String revidedID = null;

  @SerializedName("RevisionDescription")
  private String revisionDescription = null;

  @SerializedName("RevisionDate$DATE")
  private DateTime revisionDateDATE = null;

  @SerializedName("RevisionAuthor_ID")
  private String revisionAuthorID = null;

  @SerializedName("Revision")
  private Integer revision = null;

  @SerializedName("Parent_ID")
  private String parentID = null;

  @SerializedName("SecurityRole_ID")
  private String securityRoleID = null;

  @SerializedName("SecurityUser_ID")
  private String securityUserID = null;

  @SerializedName("DocumentCompetence")
  private Integer documentCompetence = null;

   /**
   * Název
   * @return displayName
  **/
  @ApiModelProperty(example = "null", value = "Název")
  public String getDisplayName() {
    return displayName;
  }

   /**
   * Vlastní ID [persistentní položka]
   * @return ID
  **/
  @ApiModelProperty(example = "null", value = "Vlastní ID [persistentní položka]")
  public String getID() {
    return ID;
  }

   /**
   * ID třídy
   * @return classID
  **/
  @ApiModelProperty(example = "null", value = "ID třídy")
  public String getClassID() {
    return classID;
  }

   /**
   * Verze objektu [persistentní položka]
   * @return objVersion
  **/
  @ApiModelProperty(example = "null", value = "Verze objektu [persistentní položka]")
  public Integer getObjVersion() {
    return objVersion;
  }

   /**
   * ID revidovaného objektu; ID objektu Účastník dokumentu
   * @return revidedID
  **/
  @ApiModelProperty(example = "null", value = "ID revidovaného objektu; ID objektu Účastník dokumentu")
  public String getRevidedID() {
    return revidedID;
  }

   /**
   * Popis revize
   * @return revisionDescription
  **/
  @ApiModelProperty(example = "null", value = "Popis revize")
  public String getRevisionDescription() {
    return revisionDescription;
  }

   /**
   * Datum revize
   * @return revisionDateDATE
  **/
  @ApiModelProperty(example = "null", value = "Datum revize")
  public DateTime getRevisionDateDATE() {
    return revisionDateDATE;
  }

   /**
   * Autor revize; ID objektu Uživatel
   * @return revisionAuthorID
  **/
  @ApiModelProperty(example = "null", value = "Autor revize; ID objektu Uživatel")
  public String getRevisionAuthorID() {
    return revisionAuthorID;
  }

   /**
   * Číslo revize
   * @return revision
  **/
  @ApiModelProperty(example = "null", value = "Číslo revize")
  public Integer getRevision() {
    return revision;
  }

   /**
   * Vlastník; ID objektu Dokument [persistentní položka]
   * @return parentID
  **/
  @ApiModelProperty(example = "null", value = "Vlastník; ID objektu Dokument [persistentní položka]")
  public String getParentID() {
    return parentID;
  }

  public Documentparticipant securityRoleID(String securityRoleID) {
    this.securityRoleID = securityRoleID;
    return this;
  }

   /**
   * Role; ID objektu Role [persistentní položka]
   * @return securityRoleID
  **/
  @ApiModelProperty(example = "null", value = "Role; ID objektu Role [persistentní položka]")
  public String getSecurityRoleID() {
    return securityRoleID;
  }

  public void setSecurityRoleID(String securityRoleID) {
    this.securityRoleID = securityRoleID;
  }

  public Documentparticipant securityUserID(String securityUserID) {
    this.securityUserID = securityUserID;
    return this;
  }

   /**
   * Uživatel; ID objektu Uživatel [persistentní položka]
   * @return securityUserID
  **/
  @ApiModelProperty(example = "null", value = "Uživatel; ID objektu Uživatel [persistentní položka]")
  public String getSecurityUserID() {
    return securityUserID;
  }

  public void setSecurityUserID(String securityUserID) {
    this.securityUserID = securityUserID;
  }

  public Documentparticipant documentCompetence(Integer documentCompetence) {
    this.documentCompetence = documentCompetence;
    return this;
  }

   /**
   * Oprávnění [persistentní položka]
   * @return documentCompetence
  **/
  @ApiModelProperty(example = "null", value = "Oprávnění [persistentní položka]")
  public Integer getDocumentCompetence() {
    return documentCompetence;
  }

  public void setDocumentCompetence(Integer documentCompetence) {
    this.documentCompetence = documentCompetence;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Documentparticipant documentparticipant = (Documentparticipant) o;
    return Objects.equals(this.displayName, documentparticipant.displayName) &&
        Objects.equals(this.ID, documentparticipant.ID) &&
        Objects.equals(this.classID, documentparticipant.classID) &&
        Objects.equals(this.objVersion, documentparticipant.objVersion) &&
        Objects.equals(this.revidedID, documentparticipant.revidedID) &&
        Objects.equals(this.revisionDescription, documentparticipant.revisionDescription) &&
        Objects.equals(this.revisionDateDATE, documentparticipant.revisionDateDATE) &&
        Objects.equals(this.revisionAuthorID, documentparticipant.revisionAuthorID) &&
        Objects.equals(this.revision, documentparticipant.revision) &&
        Objects.equals(this.parentID, documentparticipant.parentID) &&
        Objects.equals(this.securityRoleID, documentparticipant.securityRoleID) &&
        Objects.equals(this.securityUserID, documentparticipant.securityUserID) &&
        Objects.equals(this.documentCompetence, documentparticipant.documentCompetence);
  }

  @Override
  public int hashCode() {
    return Objects.hash(displayName, ID, classID, objVersion, revidedID, revisionDescription, revisionDateDATE, revisionAuthorID, revision, parentID, securityRoleID, securityUserID, documentCompetence);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Documentparticipant {\n");
    
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    ID: ").append(toIndentedString(ID)).append("\n");
    sb.append("    classID: ").append(toIndentedString(classID)).append("\n");
    sb.append("    objVersion: ").append(toIndentedString(objVersion)).append("\n");
    sb.append("    revidedID: ").append(toIndentedString(revidedID)).append("\n");
    sb.append("    revisionDescription: ").append(toIndentedString(revisionDescription)).append("\n");
    sb.append("    revisionDateDATE: ").append(toIndentedString(revisionDateDATE)).append("\n");
    sb.append("    revisionAuthorID: ").append(toIndentedString(revisionAuthorID)).append("\n");
    sb.append("    revision: ").append(toIndentedString(revision)).append("\n");
    sb.append("    parentID: ").append(toIndentedString(parentID)).append("\n");
    sb.append("    securityRoleID: ").append(toIndentedString(securityRoleID)).append("\n");
    sb.append("    securityUserID: ").append(toIndentedString(securityUserID)).append("\n");
    sb.append("    documentCompetence: ").append(toIndentedString(documentCompetence)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

