/**
 * ABRA Gen Web API (spojení testapi)
 * Webové API systému 17.03.03
 *
 * OpenAPI spec version: 17.03.03
 * Contact: abragen@abra.eu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package application.service.abra.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;

import java.util.Objects;


/**
 * Firmbankaccount
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-03-26T20:30:15.152+02:00")
public class Firmbankaccount   {
  @SerializedName("DisplayName")
  private String displayName = null;

  @SerializedName("ID")
  private String ID = null;

  @SerializedName("ClassID")
  private String classID = null;

  @SerializedName("ObjVersion")
  private Integer objVersion = null;

  @SerializedName("Parent_ID")
  private String parentID = null;

  @SerializedName("PosIndex")
  private Integer posIndex = null;

  @SerializedName("Name")
  private String name = null;

  @SerializedName("BankAccount")
  private String bankAccount = null;

  @SerializedName("SpecSymbol")
  private String specSymbol = null;

  @SerializedName("Address_ID")
  private Firmbankaccount addressID = null;

  @SerializedName("SwiftCode")
  private String swiftCode = null;

  @SerializedName("BankCountry_ID")
  private String bankCountryID = null;

  @SerializedName("PublishedStatus")
  private Integer publishedStatus = null;

  @SerializedName("PublishedStatusAsText")
  private String publishedStatusAsText = null;

  @SerializedName("PublishedDate$DATE")
  private DateTime publishedDateDATE = null;

  @SerializedName("PublishedEndDate$DATE")
  private DateTime publishedEndDateDATE = null;

   /**
   * Název
   * @return displayName
  **/
  @ApiModelProperty(example = "null", value = "Název")
  public String getDisplayName() {
    return displayName;
  }

   /**
   * Vlastní ID [persistentní položka]
   * @return ID
  **/
  @ApiModelProperty(example = "null", value = "Vlastní ID [persistentní položka]")
  public String getID() {
    return ID;
  }

   /**
   * ID třídy
   * @return classID
  **/
  @ApiModelProperty(example = "null", value = "ID třídy")
  public String getClassID() {
    return classID;
  }

   /**
   * Verze objektu [persistentní položka]
   * @return objVersion
  **/
  @ApiModelProperty(example = "null", value = "Verze objektu [persistentní položka]")
  public Integer getObjVersion() {
    return objVersion;
  }

   /**
   * Vlastník; ID objektu Firma [persistentní položka]
   * @return parentID
  **/
  @ApiModelProperty(example = "null", value = "Vlastník; ID objektu Firma [persistentní položka]")
  public String getParentID() {
    return parentID;
  }

  public Firmbankaccount posIndex(Integer posIndex) {
    this.posIndex = posIndex;
    return this;
  }

   /**
   * Pořadí [persistentní položka]
   * @return posIndex
  **/
  @ApiModelProperty(example = "null", value = "Pořadí [persistentní položka]")
  public Integer getPosIndex() {
    return posIndex;
  }

  public void setPosIndex(Integer posIndex) {
    this.posIndex = posIndex;
  }

  public Firmbankaccount name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Název [persistentní položka]
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "Název [persistentní položka]")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Firmbankaccount bankAccount(String bankAccount) {
    this.bankAccount = bankAccount;
    return this;
  }

   /**
   * Účet [persistentní položka]
   * @return bankAccount
  **/
  @ApiModelProperty(example = "null", value = "Účet [persistentní položka]")
  public String getBankAccount() {
    return bankAccount;
  }

  public void setBankAccount(String bankAccount) {
    this.bankAccount = bankAccount;
  }

  public Firmbankaccount specSymbol(String specSymbol) {
    this.specSymbol = specSymbol;
    return this;
  }

   /**
   * Specifický symbol [persistentní položka]
   * @return specSymbol
  **/
  @ApiModelProperty(example = "null", value = "Specifický symbol [persistentní položka]")
  public String getSpecSymbol() {
    return specSymbol;
  }

  public void setSpecSymbol(String specSymbol) {
    this.specSymbol = specSymbol;
  }

  public Firmbankaccount addressID(Firmbankaccount addressID) {
    this.addressID = addressID;
    return this;
  }

   /**
   * Get addressID
   * @return addressID
  **/
  @ApiModelProperty(example = "null", value = "")
  public Firmbankaccount getAddressID() {
    return addressID;
  }

  public void setAddressID(Firmbankaccount addressID) {
    this.addressID = addressID;
  }

  public Firmbankaccount swiftCode(String swiftCode) {
    this.swiftCode = swiftCode;
    return this;
  }

   /**
   * SWIFT [persistentní položka]
   * @return swiftCode
  **/
  @ApiModelProperty(example = "null", value = "SWIFT [persistentní položka]")
  public String getSwiftCode() {
    return swiftCode;
  }

  public void setSwiftCode(String swiftCode) {
    this.swiftCode = swiftCode;
  }

  public Firmbankaccount bankCountryID(String bankCountryID) {
    this.bankCountryID = bankCountryID;
    return this;
  }

   /**
   * Země banky; ID objektu Země [persistentní položka]
   * @return bankCountryID
  **/
  @ApiModelProperty(example = "null", value = "Země banky; ID objektu Země [persistentní položka]")
  public String getBankCountryID() {
    return bankCountryID;
  }

  public void setBankCountryID(String bankCountryID) {
    this.bankCountryID = bankCountryID;
  }

   /**
   * Status účtu
   * @return publishedStatus
  **/
  @ApiModelProperty(example = "null", value = "Status účtu")
  public Integer getPublishedStatus() {
    return publishedStatus;
  }

   /**
   * Status účtu - text
   * @return publishedStatusAsText
  **/
  @ApiModelProperty(example = "null", value = "Status účtu - text")
  public String getPublishedStatusAsText() {
    return publishedStatusAsText;
  }

   /**
   * Datum zveřejnění
   * @return publishedDateDATE
  **/
  @ApiModelProperty(example = "null", value = "Datum zveřejnění")
  public DateTime getPublishedDateDATE() {
    return publishedDateDATE;
  }

   /**
   * Datum konce zveřejnění
   * @return publishedEndDateDATE
  **/
  @ApiModelProperty(example = "null", value = "Datum konce zveřejnění")
  public DateTime getPublishedEndDateDATE() {
    return publishedEndDateDATE;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Firmbankaccount firmbankaccount = (Firmbankaccount) o;
    return Objects.equals(this.displayName, firmbankaccount.displayName) &&
        Objects.equals(this.ID, firmbankaccount.ID) &&
        Objects.equals(this.classID, firmbankaccount.classID) &&
        Objects.equals(this.objVersion, firmbankaccount.objVersion) &&
        Objects.equals(this.parentID, firmbankaccount.parentID) &&
        Objects.equals(this.posIndex, firmbankaccount.posIndex) &&
        Objects.equals(this.name, firmbankaccount.name) &&
        Objects.equals(this.bankAccount, firmbankaccount.bankAccount) &&
        Objects.equals(this.specSymbol, firmbankaccount.specSymbol) &&
        Objects.equals(this.addressID, firmbankaccount.addressID) &&
        Objects.equals(this.swiftCode, firmbankaccount.swiftCode) &&
        Objects.equals(this.bankCountryID, firmbankaccount.bankCountryID) &&
        Objects.equals(this.publishedStatus, firmbankaccount.publishedStatus) &&
        Objects.equals(this.publishedStatusAsText, firmbankaccount.publishedStatusAsText) &&
        Objects.equals(this.publishedDateDATE, firmbankaccount.publishedDateDATE) &&
        Objects.equals(this.publishedEndDateDATE, firmbankaccount.publishedEndDateDATE);
  }

  @Override
  public int hashCode() {
    return Objects.hash(displayName, ID, classID, objVersion, parentID, posIndex, name, bankAccount, specSymbol, addressID, swiftCode, bankCountryID, publishedStatus, publishedStatusAsText, publishedDateDATE, publishedEndDateDATE);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Firmbankaccount {\n");
    
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    ID: ").append(toIndentedString(ID)).append("\n");
    sb.append("    classID: ").append(toIndentedString(classID)).append("\n");
    sb.append("    objVersion: ").append(toIndentedString(objVersion)).append("\n");
    sb.append("    parentID: ").append(toIndentedString(parentID)).append("\n");
    sb.append("    posIndex: ").append(toIndentedString(posIndex)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    bankAccount: ").append(toIndentedString(bankAccount)).append("\n");
    sb.append("    specSymbol: ").append(toIndentedString(specSymbol)).append("\n");
    sb.append("    addressID: ").append(toIndentedString(addressID)).append("\n");
    sb.append("    swiftCode: ").append(toIndentedString(swiftCode)).append("\n");
    sb.append("    bankCountryID: ").append(toIndentedString(bankCountryID)).append("\n");
    sb.append("    publishedStatus: ").append(toIndentedString(publishedStatus)).append("\n");
    sb.append("    publishedStatusAsText: ").append(toIndentedString(publishedStatusAsText)).append("\n");
    sb.append("    publishedDateDATE: ").append(toIndentedString(publishedDateDATE)).append("\n");
    sb.append("    publishedEndDateDATE: ").append(toIndentedString(publishedEndDateDATE)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

