/**
 * abra gen web api (spojení testapi)
 * webové api systému 17.03.03
 *
 * OpenAPI spec version: 17.03.03
 * Contact: abragen@abra.eu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package application.service.abra.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


/**
 * Plmreqoutputitem
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-03-29T11:52:08.096+02:00")
public class Plmreqoutputitem   {
  @SerializedName("displayname")
  private String displayname = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("classid")
  private String classid = null;

  @SerializedName("objversion")
  private Integer objversion = null;

  @SerializedName("plmreqroutines")
  private List<Plmreqroutine> plmreqroutines = new ArrayList<Plmreqroutine>();

  @SerializedName("quantity")
  private Double quantity = null;

  @SerializedName("qunit")
  private String qunit = null;

  @SerializedName("unitrate")
  private Double unitrate = null;

  @SerializedName("routinetype_id")
  private String routinetypeId = null;

  @SerializedName("unitquantity")
  private Double unitquantity = null;

  @SerializedName("plquantity")
  private Double plquantity = null;

  @SerializedName("plqunit")
  private String plqunit = null;

  @SerializedName("plunitrate")
  private Double plunitrate = null;

  @SerializedName("routinequantity")
  private Double routinequantity = null;

  @SerializedName("routinequnit")
  private String routinequnit = null;

  @SerializedName("routineunitrate")
  private Double routineunitrate = null;

  @SerializedName("plunitquantity")
  private Double plunitquantity = null;

  @SerializedName("routineunitquantity")
  private Double routineunitquantity = null;

  @SerializedName("routinestorecard_id")
  private String routinestorecardId = null;

  @SerializedName("routinenote")
  private String routinenote = null;

  @SerializedName("plnote")
  private String plnote = null;

  @SerializedName("routinerevision")
  private Integer routinerevision = null;

  @SerializedName("plrevision")
  private Integer plrevision = null;

  @SerializedName("owner_id")
  private String ownerId = null;

  public Plmreqoutputitem displayname(String displayname) {
    this.displayname = displayname;
    return this;
  }

   /**
   * název
   * @return displayname
  **/
  @ApiModelProperty(example = "null", value = "název")
  public String getDisplayname() {
    return displayname;
  }

  public void setDisplayname(String displayname) {
    this.displayname = displayname;
  }

  public Plmreqoutputitem id(String id) {
    this.id = id;
    return this;
  }

   /**
   * vlastní id [persistentní položka]
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "vlastní id [persistentní položka]")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Plmreqoutputitem classid(String classid) {
    this.classid = classid;
    return this;
  }

   /**
   * id třídy
   * @return classid
  **/
  @ApiModelProperty(example = "null", value = "id třídy")
  public String getClassid() {
    return classid;
  }

  public void setClassid(String classid) {
    this.classid = classid;
  }

  public Plmreqoutputitem objversion(Integer objversion) {
    this.objversion = objversion;
    return this;
  }

   /**
   * verze objektu [persistentní položka]
   * @return objversion
  **/
  @ApiModelProperty(example = "null", value = "verze objektu [persistentní položka]")
  public Integer getObjversion() {
    return objversion;
  }

  public void setObjversion(Integer objversion) {
    this.objversion = objversion;
  }

  public Plmreqoutputitem plmreqroutines(List<Plmreqroutine> plmreqroutines) {
    this.plmreqroutines = plmreqroutines;
    return this;
  }

  public Plmreqoutputitem addPlmreqroutinesItem(Plmreqroutine plmreqroutinesItem) {
    this.plmreqroutines.add(plmreqroutinesItem);
    return this;
  }

   /**
   * postupy; kolekce bo požadavek na výrobu - technologický postup [nepersistentní položka]
   * @return plmreqroutines
  **/
  @ApiModelProperty(example = "null", value = "postupy; kolekce bo požadavek na výrobu - technologický postup [nepersistentní položka]")
  public List<Plmreqroutine> getPlmreqroutines() {
    return plmreqroutines;
  }

  public void setPlmreqroutines(List<Plmreqroutine> plmreqroutines) {
    this.plmreqroutines = plmreqroutines;
  }

  public Plmreqoutputitem quantity(Double quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * množství v ev.jedn. [persistentní položka]
   * @return quantity
  **/
  @ApiModelProperty(example = "null", value = "množství v ev.jedn. [persistentní položka]")
  public Double getQuantity() {
    return quantity;
  }

  public void setQuantity(Double quantity) {
    this.quantity = quantity;
  }

  public Plmreqoutputitem qunit(String qunit) {
    this.qunit = qunit;
    return this;
  }

   /**
   * jednotka [persistentní položka]
   * @return qunit
  **/
  @ApiModelProperty(example = "null", value = "jednotka [persistentní položka]")
  public String getQunit() {
    return qunit;
  }

  public void setQunit(String qunit) {
    this.qunit = qunit;
  }

  public Plmreqoutputitem unitrate(Double unitrate) {
    this.unitrate = unitrate;
    return this;
  }

   /**
   * vztah [persistentní položka]
   * @return unitrate
  **/
  @ApiModelProperty(example = "null", value = "vztah [persistentní položka]")
  public Double getUnitrate() {
    return unitrate;
  }

  public void setUnitrate(Double unitrate) {
    this.unitrate = unitrate;
  }

  public Plmreqoutputitem routinetypeId(String routinetypeId) {
    this.routinetypeId = routinetypeId;
    return this;
  }

   /**
   * typ postupu; id objektu typ technologického postupu [persistentní položka]
   * @return routinetypeId
  **/
  @ApiModelProperty(example = "null", value = "typ postupu; id objektu typ technologického postupu [persistentní položka]")
  public String getRoutinetypeId() {
    return routinetypeId;
  }

  public void setRoutinetypeId(String routinetypeId) {
    this.routinetypeId = routinetypeId;
  }

  public Plmreqoutputitem unitquantity(Double unitquantity) {
    this.unitquantity = unitquantity;
    return this;
  }

   /**
   * množství
   * @return unitquantity
  **/
  @ApiModelProperty(example = "null", value = "množství")
  public Double getUnitquantity() {
    return unitquantity;
  }

  public void setUnitquantity(Double unitquantity) {
    this.unitquantity = unitquantity;
  }

  public Plmreqoutputitem plquantity(Double plquantity) {
    this.plquantity = plquantity;
    return this;
  }

   /**
   * množství [persistentní položka]
   * @return plquantity
  **/
  @ApiModelProperty(example = "null", value = "množství [persistentní položka]")
  public Double getPlquantity() {
    return plquantity;
  }

  public void setPlquantity(Double plquantity) {
    this.plquantity = plquantity;
  }

  public Plmreqoutputitem plqunit(String plqunit) {
    this.plqunit = plqunit;
    return this;
  }

   /**
   * jednotka [persistentní položka]
   * @return plqunit
  **/
  @ApiModelProperty(example = "null", value = "jednotka [persistentní položka]")
  public String getPlqunit() {
    return plqunit;
  }

  public void setPlqunit(String plqunit) {
    this.plqunit = plqunit;
  }

  public Plmreqoutputitem plunitrate(Double plunitrate) {
    this.plunitrate = plunitrate;
    return this;
  }

   /**
   * vztah [persistentní položka]
   * @return plunitrate
  **/
  @ApiModelProperty(example = "null", value = "vztah [persistentní položka]")
  public Double getPlunitrate() {
    return plunitrate;
  }

  public void setPlunitrate(Double plunitrate) {
    this.plunitrate = plunitrate;
  }

  public Plmreqoutputitem routinequantity(Double routinequantity) {
    this.routinequantity = routinequantity;
    return this;
  }

   /**
   * množství [persistentní položka]
   * @return routinequantity
  **/
  @ApiModelProperty(example = "null", value = "množství [persistentní položka]")
  public Double getRoutinequantity() {
    return routinequantity;
  }

  public void setRoutinequantity(Double routinequantity) {
    this.routinequantity = routinequantity;
  }

  public Plmreqoutputitem routinequnit(String routinequnit) {
    this.routinequnit = routinequnit;
    return this;
  }

   /**
   * jednotka [persistentní položka]
   * @return routinequnit
  **/
  @ApiModelProperty(example = "null", value = "jednotka [persistentní položka]")
  public String getRoutinequnit() {
    return routinequnit;
  }

  public void setRoutinequnit(String routinequnit) {
    this.routinequnit = routinequnit;
  }

  public Plmreqoutputitem routineunitrate(Double routineunitrate) {
    this.routineunitrate = routineunitrate;
    return this;
  }

   /**
   * vztah [persistentní položka]
   * @return routineunitrate
  **/
  @ApiModelProperty(example = "null", value = "vztah [persistentní položka]")
  public Double getRoutineunitrate() {
    return routineunitrate;
  }

  public void setRoutineunitrate(Double routineunitrate) {
    this.routineunitrate = routineunitrate;
  }

  public Plmreqoutputitem plunitquantity(Double plunitquantity) {
    this.plunitquantity = plunitquantity;
    return this;
  }

   /**
   * množství
   * @return plunitquantity
  **/
  @ApiModelProperty(example = "null", value = "množství")
  public Double getPlunitquantity() {
    return plunitquantity;
  }

  public void setPlunitquantity(Double plunitquantity) {
    this.plunitquantity = plunitquantity;
  }

  public Plmreqoutputitem routineunitquantity(Double routineunitquantity) {
    this.routineunitquantity = routineunitquantity;
    return this;
  }

   /**
   * množství
   * @return routineunitquantity
  **/
  @ApiModelProperty(example = "null", value = "množství")
  public Double getRoutineunitquantity() {
    return routineunitquantity;
  }

  public void setRoutineunitquantity(Double routineunitquantity) {
    this.routineunitquantity = routineunitquantity;
  }

  public Plmreqoutputitem routinestorecardId(String routinestorecardId) {
    this.routinestorecardId = routinestorecardId;
    return this;
  }

   /**
   * skladová karta tp; id objektu skladová karta [persistentní položka]
   * @return routinestorecardId
  **/
  @ApiModelProperty(example = "null", value = "skladová karta tp; id objektu skladová karta [persistentní položka]")
  public String getRoutinestorecardId() {
    return routinestorecardId;
  }

  public void setRoutinestorecardId(String routinestorecardId) {
    this.routinestorecardId = routinestorecardId;
  }

  public Plmreqoutputitem routinenote(String routinenote) {
    this.routinenote = routinenote;
    return this;
  }

   /**
   * poznámka z tp [persistentní položka]
   * @return routinenote
  **/
  @ApiModelProperty(example = "null", value = "poznámka z tp [persistentní položka]")
  public String getRoutinenote() {
    return routinenote;
  }

  public void setRoutinenote(String routinenote) {
    this.routinenote = routinenote;
  }

  public Plmreqoutputitem plnote(String plnote) {
    this.plnote = plnote;
    return this;
  }

   /**
   * poznámka z pl [persistentní položka]
   * @return plnote
  **/
  @ApiModelProperty(example = "null", value = "poznámka z pl [persistentní položka]")
  public String getPlnote() {
    return plnote;
  }

  public void setPlnote(String plnote) {
    this.plnote = plnote;
  }

  public Plmreqoutputitem routinerevision(Integer routinerevision) {
    this.routinerevision = routinerevision;
    return this;
  }

   /**
   * revize tp [persistentní položka]
   * @return routinerevision
  **/
  @ApiModelProperty(example = "null", value = "revize tp [persistentní položka]")
  public Integer getRoutinerevision() {
    return routinerevision;
  }

  public void setRoutinerevision(Integer routinerevision) {
    this.routinerevision = routinerevision;
  }

  public Plmreqoutputitem plrevision(Integer plrevision) {
    this.plrevision = plrevision;
    return this;
  }

   /**
   * revize kus. [persistentní položka]
   * @return plrevision
  **/
  @ApiModelProperty(example = "null", value = "revize kus. [persistentní položka]")
  public Integer getPlrevision() {
    return plrevision;
  }

  public void setPlrevision(Integer plrevision) {
    this.plrevision = plrevision;
  }

  public Plmreqoutputitem ownerId(String ownerId) {
    this.ownerId = ownerId;
    return this;
  }

   /**
   * vlastník; id objektu uzel stromu požadavku na výrobu [persistentní položka]
   * @return ownerId
  **/
  @ApiModelProperty(example = "null", value = "vlastník; id objektu uzel stromu požadavku na výrobu [persistentní položka]")
  public String getOwnerId() {
    return ownerId;
  }

  public void setOwnerId(String ownerId) {
    this.ownerId = ownerId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Plmreqoutputitem plmreqoutputitem = (Plmreqoutputitem) o;
    return Objects.equals(this.displayname, plmreqoutputitem.displayname) &&
        Objects.equals(this.id, plmreqoutputitem.id) &&
        Objects.equals(this.classid, plmreqoutputitem.classid) &&
        Objects.equals(this.objversion, plmreqoutputitem.objversion) &&
        Objects.equals(this.plmreqroutines, plmreqoutputitem.plmreqroutines) &&
        Objects.equals(this.quantity, plmreqoutputitem.quantity) &&
        Objects.equals(this.qunit, plmreqoutputitem.qunit) &&
        Objects.equals(this.unitrate, plmreqoutputitem.unitrate) &&
        Objects.equals(this.routinetypeId, plmreqoutputitem.routinetypeId) &&
        Objects.equals(this.unitquantity, plmreqoutputitem.unitquantity) &&
        Objects.equals(this.plquantity, plmreqoutputitem.plquantity) &&
        Objects.equals(this.plqunit, plmreqoutputitem.plqunit) &&
        Objects.equals(this.plunitrate, plmreqoutputitem.plunitrate) &&
        Objects.equals(this.routinequantity, plmreqoutputitem.routinequantity) &&
        Objects.equals(this.routinequnit, plmreqoutputitem.routinequnit) &&
        Objects.equals(this.routineunitrate, plmreqoutputitem.routineunitrate) &&
        Objects.equals(this.plunitquantity, plmreqoutputitem.plunitquantity) &&
        Objects.equals(this.routineunitquantity, plmreqoutputitem.routineunitquantity) &&
        Objects.equals(this.routinestorecardId, plmreqoutputitem.routinestorecardId) &&
        Objects.equals(this.routinenote, plmreqoutputitem.routinenote) &&
        Objects.equals(this.plnote, plmreqoutputitem.plnote) &&
        Objects.equals(this.routinerevision, plmreqoutputitem.routinerevision) &&
        Objects.equals(this.plrevision, plmreqoutputitem.plrevision) &&
        Objects.equals(this.ownerId, plmreqoutputitem.ownerId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(displayname, id, classid, objversion, plmreqroutines, quantity, qunit, unitrate, routinetypeId, unitquantity, plquantity, plqunit, plunitrate, routinequantity, routinequnit, routineunitrate, plunitquantity, routineunitquantity, routinestorecardId, routinenote, plnote, routinerevision, plrevision, ownerId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Plmreqoutputitem {\n");
    
    sb.append("    displayname: ").append(toIndentedString(displayname)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    classid: ").append(toIndentedString(classid)).append("\n");
    sb.append("    objversion: ").append(toIndentedString(objversion)).append("\n");
    sb.append("    plmreqroutines: ").append(toIndentedString(plmreqroutines)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    qunit: ").append(toIndentedString(qunit)).append("\n");
    sb.append("    unitrate: ").append(toIndentedString(unitrate)).append("\n");
    sb.append("    routinetypeId: ").append(toIndentedString(routinetypeId)).append("\n");
    sb.append("    unitquantity: ").append(toIndentedString(unitquantity)).append("\n");
    sb.append("    plquantity: ").append(toIndentedString(plquantity)).append("\n");
    sb.append("    plqunit: ").append(toIndentedString(plqunit)).append("\n");
    sb.append("    plunitrate: ").append(toIndentedString(plunitrate)).append("\n");
    sb.append("    routinequantity: ").append(toIndentedString(routinequantity)).append("\n");
    sb.append("    routinequnit: ").append(toIndentedString(routinequnit)).append("\n");
    sb.append("    routineunitrate: ").append(toIndentedString(routineunitrate)).append("\n");
    sb.append("    plunitquantity: ").append(toIndentedString(plunitquantity)).append("\n");
    sb.append("    routineunitquantity: ").append(toIndentedString(routineunitquantity)).append("\n");
    sb.append("    routinestorecardId: ").append(toIndentedString(routinestorecardId)).append("\n");
    sb.append("    routinenote: ").append(toIndentedString(routinenote)).append("\n");
    sb.append("    plnote: ").append(toIndentedString(plnote)).append("\n");
    sb.append("    routinerevision: ").append(toIndentedString(routinerevision)).append("\n");
    sb.append("    plrevision: ").append(toIndentedString(plrevision)).append("\n");
    sb.append("    ownerId: ").append(toIndentedString(ownerId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

