/**
 * ABRA Gen Web API (spojení testapi)
 * Webové API systému 17.03.03
 *
 * OpenAPI spec version: 17.03.03
 * Contact: abragen@abra.eu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package application.service.abra.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


/**
 * Supplierpricelist
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-03-26T20:30:15.152+02:00")
public class Supplierpricelist   {
  @SerializedName("DisplayName")
  private String displayName = null;

  @SerializedName("ID")
  private String ID = null;

  @SerializedName("ClassID")
  private String classID = null;

  @SerializedName("ObjVersion")
  private Integer objVersion = null;

  @SerializedName("Rows")
  private List<Supplierpricelistrow> rows = new ArrayList<Supplierpricelistrow>();

  @SerializedName("Firm_ID")
  private String firmID = null;

  @SerializedName("FirmOffice_ID")
  private String firmOfficeID = null;

  @SerializedName("Person_ID")
  private String personID = null;

  @SerializedName("Code")
  private String code = null;

  @SerializedName("Name")
  private String name = null;

  @SerializedName("ValidFromDate$DATE")
  private DateTime validFromDateDATE = null;

  @SerializedName("LastImportDate$DATE")
  private DateTime lastImportDateDATE = null;

  @SerializedName("Country_ID")
  private String countryID = null;

  @SerializedName("Discount1")
  private Double discount1 = null;

  @SerializedName("Discount2")
  private Double discount2 = null;

  @SerializedName("Discount3")
  private Double discount3 = null;

  @SerializedName("PricesWithVAT")
  private Boolean pricesWithVAT = null;

  @SerializedName("Note")
  private String note = null;

  @SerializedName("TotalDiscount")
  private Double totalDiscount = null;

  @SerializedName("CountOfAssigned")
  private Integer countOfAssigned = null;

  @SerializedName("CountOfUnAssigned")
  private Integer countOfUnAssigned = null;

   /**
   * Název
   * @return displayName
  **/
  @ApiModelProperty(example = "null", value = "Název")
  public String getDisplayName() {
    return displayName;
  }

   /**
   * Vlastní ID [persistentní položka]
   * @return ID
  **/
  @ApiModelProperty(example = "null", value = "Vlastní ID [persistentní položka]")
  public String getID() {
    return ID;
  }

   /**
   * ID třídy
   * @return classID
  **/
  @ApiModelProperty(example = "null", value = "ID třídy")
  public String getClassID() {
    return classID;
  }

   /**
   * Verze objektu [persistentní položka]
   * @return objVersion
  **/
  @ApiModelProperty(example = "null", value = "Verze objektu [persistentní položka]")
  public Integer getObjVersion() {
    return objVersion;
  }

  public Supplierpricelist rows(List<Supplierpricelistrow> rows) {
    this.rows = rows;
    return this;
  }

  public Supplierpricelist addRowsItem(Supplierpricelistrow rowsItem) {
    this.rows.add(rowsItem);
    return this;
  }

   /**
   * Řádky; kolekce BO Položka dod. ceníku [nepersistentní položka]
   * @return rows
  **/
  @ApiModelProperty(example = "null", value = "Řádky; kolekce BO Položka dod. ceníku [nepersistentní položka]")
  public List<Supplierpricelistrow> getRows() {
    return rows;
  }

  public void setRows(List<Supplierpricelistrow> rows) {
    this.rows = rows;
  }

  public Supplierpricelist firmID(String firmID) {
    this.firmID = firmID;
    return this;
  }

   /**
   * Firma; ID objektu Firma [persistentní položka]
   * @return firmID
  **/
  @ApiModelProperty(example = "null", value = "Firma; ID objektu Firma [persistentní položka]")
  public String getFirmID() {
    return firmID;
  }

  public void setFirmID(String firmID) {
    this.firmID = firmID;
  }

  public Supplierpricelist firmOfficeID(String firmOfficeID) {
    this.firmOfficeID = firmOfficeID;
    return this;
  }

   /**
   * Provozovna; ID objektu Provozovna [persistentní položka]
   * @return firmOfficeID
  **/
  @ApiModelProperty(example = "null", value = "Provozovna; ID objektu Provozovna [persistentní položka]")
  public String getFirmOfficeID() {
    return firmOfficeID;
  }

  public void setFirmOfficeID(String firmOfficeID) {
    this.firmOfficeID = firmOfficeID;
  }

  public Supplierpricelist personID(String personID) {
    this.personID = personID;
    return this;
  }

   /**
   * Osoba; ID objektu Osoba [persistentní položka]
   * @return personID
  **/
  @ApiModelProperty(example = "null", value = "Osoba; ID objektu Osoba [persistentní položka]")
  public String getPersonID() {
    return personID;
  }

  public void setPersonID(String personID) {
    this.personID = personID;
  }

  public Supplierpricelist code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Kód [persistentní položka]
   * @return code
  **/
  @ApiModelProperty(example = "null", value = "Kód [persistentní položka]")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public Supplierpricelist name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Název [persistentní položka]
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "Název [persistentní položka]")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Supplierpricelist validFromDateDATE(DateTime validFromDateDATE) {
    this.validFromDateDATE = validFromDateDATE;
    return this;
  }

   /**
   * Platný od [persistentní položka]
   * @return validFromDateDATE
  **/
  @ApiModelProperty(example = "null", value = "Platný od [persistentní položka]")
  public DateTime getValidFromDateDATE() {
    return validFromDateDATE;
  }

  public void setValidFromDateDATE(DateTime validFromDateDATE) {
    this.validFromDateDATE = validFromDateDATE;
  }

  public Supplierpricelist lastImportDateDATE(DateTime lastImportDateDATE) {
    this.lastImportDateDATE = lastImportDateDATE;
    return this;
  }

   /**
   * Datum importu [persistentní položka]
   * @return lastImportDateDATE
  **/
  @ApiModelProperty(example = "null", value = "Datum importu [persistentní položka]")
  public DateTime getLastImportDateDATE() {
    return lastImportDateDATE;
  }

  public void setLastImportDateDATE(DateTime lastImportDateDATE) {
    this.lastImportDateDATE = lastImportDateDATE;
  }

  public Supplierpricelist countryID(String countryID) {
    this.countryID = countryID;
    return this;
  }

   /**
   * Země; ID objektu Země [persistentní položka]
   * @return countryID
  **/
  @ApiModelProperty(example = "null", value = "Země; ID objektu Země [persistentní položka]")
  public String getCountryID() {
    return countryID;
  }

  public void setCountryID(String countryID) {
    this.countryID = countryID;
  }

  public Supplierpricelist discount1(Double discount1) {
    this.discount1 = discount1;
    return this;
  }

   /**
   * Sleva 1 [persistentní položka]
   * @return discount1
  **/
  @ApiModelProperty(example = "null", value = "Sleva 1 [persistentní položka]")
  public Double getDiscount1() {
    return discount1;
  }

  public void setDiscount1(Double discount1) {
    this.discount1 = discount1;
  }

  public Supplierpricelist discount2(Double discount2) {
    this.discount2 = discount2;
    return this;
  }

   /**
   * Sleva 2 [persistentní položka]
   * @return discount2
  **/
  @ApiModelProperty(example = "null", value = "Sleva 2 [persistentní položka]")
  public Double getDiscount2() {
    return discount2;
  }

  public void setDiscount2(Double discount2) {
    this.discount2 = discount2;
  }

  public Supplierpricelist discount3(Double discount3) {
    this.discount3 = discount3;
    return this;
  }

   /**
   * Sleva 3 [persistentní položka]
   * @return discount3
  **/
  @ApiModelProperty(example = "null", value = "Sleva 3 [persistentní položka]")
  public Double getDiscount3() {
    return discount3;
  }

  public void setDiscount3(Double discount3) {
    this.discount3 = discount3;
  }

  public Supplierpricelist pricesWithVAT(Boolean pricesWithVAT) {
    this.pricesWithVAT = pricesWithVAT;
    return this;
  }

   /**
   * Cena s DPH [persistentní položka]
   * @return pricesWithVAT
  **/
  @ApiModelProperty(example = "null", value = "Cena s DPH [persistentní položka]")
  public Boolean getPricesWithVAT() {
    return pricesWithVAT;
  }

  public void setPricesWithVAT(Boolean pricesWithVAT) {
    this.pricesWithVAT = pricesWithVAT;
  }

  public Supplierpricelist note(String note) {
    this.note = note;
    return this;
  }

   /**
   * Poznámka [persistentní položka]
   * @return note
  **/
  @ApiModelProperty(example = "null", value = "Poznámka [persistentní položka]")
  public String getNote() {
    return note;
  }

  public void setNote(String note) {
    this.note = note;
  }

  public Supplierpricelist totalDiscount(Double totalDiscount) {
    this.totalDiscount = totalDiscount;
    return this;
  }

   /**
   * Celková sleva
   * @return totalDiscount
  **/
  @ApiModelProperty(example = "null", value = "Celková sleva")
  public Double getTotalDiscount() {
    return totalDiscount;
  }

  public void setTotalDiscount(Double totalDiscount) {
    this.totalDiscount = totalDiscount;
  }

  public Supplierpricelist countOfAssigned(Integer countOfAssigned) {
    this.countOfAssigned = countOfAssigned;
    return this;
  }

   /**
   * Připojených
   * @return countOfAssigned
  **/
  @ApiModelProperty(example = "null", value = "Připojených")
  public Integer getCountOfAssigned() {
    return countOfAssigned;
  }

  public void setCountOfAssigned(Integer countOfAssigned) {
    this.countOfAssigned = countOfAssigned;
  }

  public Supplierpricelist countOfUnAssigned(Integer countOfUnAssigned) {
    this.countOfUnAssigned = countOfUnAssigned;
    return this;
  }

   /**
   * Nepřipojených
   * @return countOfUnAssigned
  **/
  @ApiModelProperty(example = "null", value = "Nepřipojených")
  public Integer getCountOfUnAssigned() {
    return countOfUnAssigned;
  }

  public void setCountOfUnAssigned(Integer countOfUnAssigned) {
    this.countOfUnAssigned = countOfUnAssigned;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Supplierpricelist supplierpricelist = (Supplierpricelist) o;
    return Objects.equals(this.displayName, supplierpricelist.displayName) &&
        Objects.equals(this.ID, supplierpricelist.ID) &&
        Objects.equals(this.classID, supplierpricelist.classID) &&
        Objects.equals(this.objVersion, supplierpricelist.objVersion) &&
        Objects.equals(this.rows, supplierpricelist.rows) &&
        Objects.equals(this.firmID, supplierpricelist.firmID) &&
        Objects.equals(this.firmOfficeID, supplierpricelist.firmOfficeID) &&
        Objects.equals(this.personID, supplierpricelist.personID) &&
        Objects.equals(this.code, supplierpricelist.code) &&
        Objects.equals(this.name, supplierpricelist.name) &&
        Objects.equals(this.validFromDateDATE, supplierpricelist.validFromDateDATE) &&
        Objects.equals(this.lastImportDateDATE, supplierpricelist.lastImportDateDATE) &&
        Objects.equals(this.countryID, supplierpricelist.countryID) &&
        Objects.equals(this.discount1, supplierpricelist.discount1) &&
        Objects.equals(this.discount2, supplierpricelist.discount2) &&
        Objects.equals(this.discount3, supplierpricelist.discount3) &&
        Objects.equals(this.pricesWithVAT, supplierpricelist.pricesWithVAT) &&
        Objects.equals(this.note, supplierpricelist.note) &&
        Objects.equals(this.totalDiscount, supplierpricelist.totalDiscount) &&
        Objects.equals(this.countOfAssigned, supplierpricelist.countOfAssigned) &&
        Objects.equals(this.countOfUnAssigned, supplierpricelist.countOfUnAssigned);
  }

  @Override
  public int hashCode() {
    return Objects.hash(displayName, ID, classID, objVersion, rows, firmID, firmOfficeID, personID, code, name, validFromDateDATE, lastImportDateDATE, countryID, discount1, discount2, discount3, pricesWithVAT, note, totalDiscount, countOfAssigned, countOfUnAssigned);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Supplierpricelist {\n");
    
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    ID: ").append(toIndentedString(ID)).append("\n");
    sb.append("    classID: ").append(toIndentedString(classID)).append("\n");
    sb.append("    objVersion: ").append(toIndentedString(objVersion)).append("\n");
    sb.append("    rows: ").append(toIndentedString(rows)).append("\n");
    sb.append("    firmID: ").append(toIndentedString(firmID)).append("\n");
    sb.append("    firmOfficeID: ").append(toIndentedString(firmOfficeID)).append("\n");
    sb.append("    personID: ").append(toIndentedString(personID)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    validFromDateDATE: ").append(toIndentedString(validFromDateDATE)).append("\n");
    sb.append("    lastImportDateDATE: ").append(toIndentedString(lastImportDateDATE)).append("\n");
    sb.append("    countryID: ").append(toIndentedString(countryID)).append("\n");
    sb.append("    discount1: ").append(toIndentedString(discount1)).append("\n");
    sb.append("    discount2: ").append(toIndentedString(discount2)).append("\n");
    sb.append("    discount3: ").append(toIndentedString(discount3)).append("\n");
    sb.append("    pricesWithVAT: ").append(toIndentedString(pricesWithVAT)).append("\n");
    sb.append("    note: ").append(toIndentedString(note)).append("\n");
    sb.append("    totalDiscount: ").append(toIndentedString(totalDiscount)).append("\n");
    sb.append("    countOfAssigned: ").append(toIndentedString(countOfAssigned)).append("\n");
    sb.append("    countOfUnAssigned: ").append(toIndentedString(countOfUnAssigned)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

