/**
 * abra gen web api (spojení testapi)
 * webové api systému 17.03.03
 *
 * OpenAPI spec version: 17.03.03
 * Contact: abragen@abra.eu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package application.service.abra.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


/**
 * Vatclosing
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-03-29T11:52:08.096+02:00")
public class Vatclosing   {
  @SerializedName("displayname")
  private String displayname = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("classid")
  private String classid = null;

  @SerializedName("objversion")
  private Integer objversion = null;

  @SerializedName("rows")
  private List<Vatclosingdataitem> rows = new ArrayList<Vatclosingdataitem>();

  @SerializedName("description")
  private String description = null;

  @SerializedName("closingperiodtype")
  private Integer closingperiodtype = null;

  @SerializedName("datefrom$date")
  private DateTime datefromdate = null;

  @SerializedName("dateto$date")
  private DateTime datetodate = null;

  @SerializedName("closingdate$date")
  private DateTime closingdatedate = null;

  @SerializedName("sentdate$date")
  private DateTime sentdatedate = null;

  @SerializedName("vatdefinition_id")
  private String vatdefinitionId = null;

  @SerializedName("closingtype")
  private Integer closingtype = null;

  @SerializedName("previousclosing_id")
  private String previousclosingId = null;

  @SerializedName("withvatcheckreport")
  private Boolean withvatcheckreport = null;

  @SerializedName("withvatreturn")
  private Boolean withvatreturn = null;

  @SerializedName("createdby_id")
  private String createdbyId = null;

  @SerializedName("correctedby_id")
  private String correctedbyId = null;

  @SerializedName("closingparams")
  private byte[] closingparams = null;

  @SerializedName("vatcheckreportrows")
  private List<Vatclosingcheckreportrow> vatcheckreportrows = new ArrayList<Vatclosingcheckreportrow>();

  @SerializedName("country_id")
  private String countryId = null;

  @SerializedName("closingperiodtypeastext")
  private String closingperiodtypeastext = null;

  @SerializedName("closingtypeastext")
  private String closingtypeastext = null;

  @SerializedName("vatcoefficient1")
  private Double vatcoefficient1 = null;

  @SerializedName("vatcoefficient2")
  private Double vatcoefficient2 = null;

  @SerializedName("vatcoefficient3")
  private Double vatcoefficient3 = null;

  @SerializedName("mossrows")
  private List<Vatclosingmossrow> mossrows = new ArrayList<Vatclosingmossrow>();

  @SerializedName("s_sfullfillconditions79")
  private Boolean sSfullfillconditions79 = null;

  @SerializedName("s_sadviserphone")
  private String sSadviserphone = null;

  @SerializedName("s_sadviserphonepre")
  private String sSadviserphonepre = null;

  @SerializedName("s_sadvisername")
  private String sSadvisername = null;

  @SerializedName("s_sfaxnumber")
  private String sSfaxnumber = null;

  @SerializedName("s_sfaxnumberpre")
  private String sSfaxnumberpre = null;

  @SerializedName("s_sphonenumber")
  private String sSphonenumber = null;

  @SerializedName("s_sphonenumberpre")
  private String sSphonenumberpre = null;

  @SerializedName("s_sdateofadditional")
  private DateTime sSdateofadditional = null;

  @SerializedName("s_svatpayortype")
  private Integer sSvatpayortype = null;

  @SerializedName("s_snotax")
  private Boolean sSnotax = null;

  @SerializedName("s_sfinancialbureau")
  private String sSfinancialbureau = null;

  @SerializedName("s_sfirmemail")
  private String sSfirmemail = null;

  @SerializedName("s_sfirmphone")
  private String sSfirmphone = null;

  @SerializedName("s_financialbureau")
  private String sFinancialbureau = null;

  @SerializedName("s_nacecode")
  private String sNacecode = null;

  @SerializedName("s_reasonofadditive")
  private String sReasonofadditive = null;

  @SerializedName("s_fosurnamea")
  private String sFosurnamea = null;

  @SerializedName("s_authperson_firstname")
  private String sAuthpersonFirstname = null;

  @SerializedName("s_financialbureaucode")
  private String sFinancialbureaucode = null;

  @SerializedName("s_numofattachments")
  private Integer sNumofattachments = null;

  @SerializedName("s_vatpayortype")
  private Integer sVatpayortype = null;

  @SerializedName("s_fofirstnamea")
  private String sFofirstnamea = null;

  @SerializedName("s_authperson_surname")
  private String sAuthpersonSurname = null;

  @SerializedName("s_advisercode")
  private Integer sAdvisercode = null;

  @SerializedName("s_regionaloffice")
  private String sRegionaloffice = null;

  @SerializedName("s_numofsheets")
  private Integer sNumofsheets = null;

  @SerializedName("s_noitemsforcsection")
  private Boolean sNoitemsforcsection = null;

  @SerializedName("s_fotitlea")
  private String sFotitlea = null;

  @SerializedName("s_assemblyperson")
  private String sAssemblyperson = null;

  @SerializedName("s_advisertype")
  private Integer sAdvisertype = null;

  @SerializedName("s_authperson_status")
  private String sAuthpersonStatus = null;

  @SerializedName("s_regionalofficecode")
  private String sRegionalofficecode = null;

  @SerializedName("s_nextyeartaxperiodcode")
  private Integer sNextyeartaxperiodcode = null;

  @SerializedName("s_identnumber")
  private String sIdentnumber = null;

  @SerializedName("s_assemblytelephone")
  private String sAssemblytelephone = null;

  @SerializedName("s_adviserfirstname")
  private String sAdviserfirstname = null;

  @SerializedName("s_companytype")
  private Integer sCompanytype = null;

  @SerializedName("s_insolventperiod")
  private Boolean sInsolventperiod = null;

  @SerializedName("s_advisersurname")
  private String sAdvisersurname = null;

  @SerializedName("s_insolventperiodfrom")
  private DateTime sInsolventperiodfrom = null;

  @SerializedName("s_advisertitle")
  private String sAdvisertitle = null;

  @SerializedName("s_insolventperiodto")
  private DateTime sInsolventperiodto = null;

  @SerializedName("s_adviserbirthdate")
  private DateTime sAdviserbirthdate = null;

  @SerializedName("s_adviserevnum")
  private String sAdviserevnum = null;

  @SerializedName("s_adviseric")
  private String sAdviseric = null;

  @SerializedName("s_assemblyemail")
  private String sAssemblyemail = null;

  @SerializedName("s_assemblydate")
  private DateTime sAssemblydate = null;

  @SerializedName("s_dateofadditive")
  private DateTime sDateofadditive = null;

  @SerializedName("s_notax")
  private Boolean sNotax = null;

  @SerializedName("s_iban")
  private String sIban = null;

  @SerializedName("s_bic")
  private String sBic = null;

  @SerializedName("s_mossrefnumber")
  private String sMossrefnumber = null;

  @SerializedName("s_mossaccountname")
  private String sMossaccountname = null;

  @SerializedName("s_khdph_appealrefnumber")
  private String sKhdphAppealrefnumber = null;

  @SerializedName("s_khdph_appealreply")
  private Integer sKhdphAppealreply = null;

  @SerializedName("s_khdph_correctiondate")
  private DateTime sKhdphCorrectiondate = null;

  @SerializedName("s_khdph_type")
  private Integer sKhdphType = null;

  @SerializedName("s_databoxid")
  private String sDataboxid = null;

  public Vatclosing displayname(String displayname) {
    this.displayname = displayname;
    return this;
  }

   /**
   * název
   * @return displayname
  **/
  @ApiModelProperty(example = "null", value = "název")
  public String getDisplayname() {
    return displayname;
  }

  public void setDisplayname(String displayname) {
    this.displayname = displayname;
  }

  public Vatclosing id(String id) {
    this.id = id;
    return this;
  }

   /**
   * vlastní id [persistentní položka]
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "vlastní id [persistentní položka]")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Vatclosing classid(String classid) {
    this.classid = classid;
    return this;
  }

   /**
   * id třídy
   * @return classid
  **/
  @ApiModelProperty(example = "null", value = "id třídy")
  public String getClassid() {
    return classid;
  }

  public void setClassid(String classid) {
    this.classid = classid;
  }

  public Vatclosing objversion(Integer objversion) {
    this.objversion = objversion;
    return this;
  }

   /**
   * verze objektu [persistentní položka]
   * @return objversion
  **/
  @ApiModelProperty(example = "null", value = "verze objektu [persistentní položka]")
  public Integer getObjversion() {
    return objversion;
  }

  public void setObjversion(Integer objversion) {
    this.objversion = objversion;
  }

  public Vatclosing rows(List<Vatclosingdataitem> rows) {
    this.rows = rows;
    return this;
  }

  public Vatclosing addRowsItem(Vatclosingdataitem rowsItem) {
    this.rows.add(rowsItem);
    return this;
  }

   /**
   * Řádky; kolekce bo Řádek dph přiznání [nepersistentní položka]
   * @return rows
  **/
  @ApiModelProperty(example = "null", value = "Řádky; kolekce bo Řádek dph přiznání [nepersistentní položka]")
  public List<Vatclosingdataitem> getRows() {
    return rows;
  }

  public void setRows(List<Vatclosingdataitem> rows) {
    this.rows = rows;
  }

  public Vatclosing description(String description) {
    this.description = description;
    return this;
  }

   /**
   * popis [persistentní položka]
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "popis [persistentní položka]")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Vatclosing closingperiodtype(Integer closingperiodtype) {
    this.closingperiodtype = closingperiodtype;
    return this;
  }

   /**
   * zdaňovací období [persistentní položka]
   * @return closingperiodtype
  **/
  @ApiModelProperty(example = "null", value = "zdaňovací období [persistentní položka]")
  public Integer getClosingperiodtype() {
    return closingperiodtype;
  }

  public void setClosingperiodtype(Integer closingperiodtype) {
    this.closingperiodtype = closingperiodtype;
  }

  public Vatclosing datefromdate(DateTime datefromdate) {
    this.datefromdate = datefromdate;
    return this;
  }

   /**
   * datum od [persistentní položka]
   * @return datefromdate
  **/
  @ApiModelProperty(example = "null", value = "datum od [persistentní položka]")
  public DateTime getDatefromdate() {
    return datefromdate;
  }

  public void setDatefromdate(DateTime datefromdate) {
    this.datefromdate = datefromdate;
  }

  public Vatclosing datetodate(DateTime datetodate) {
    this.datetodate = datetodate;
    return this;
  }

   /**
   * datum do [persistentní položka]
   * @return datetodate
  **/
  @ApiModelProperty(example = "null", value = "datum do [persistentní položka]")
  public DateTime getDatetodate() {
    return datetodate;
  }

  public void setDatetodate(DateTime datetodate) {
    this.datetodate = datetodate;
  }

  public Vatclosing closingdatedate(DateTime closingdatedate) {
    this.closingdatedate = closingdatedate;
    return this;
  }

   /**
   * datum uzavření [persistentní položka]
   * @return closingdatedate
  **/
  @ApiModelProperty(example = "null", value = "datum uzavření [persistentní položka]")
  public DateTime getClosingdatedate() {
    return closingdatedate;
  }

  public void setClosingdatedate(DateTime closingdatedate) {
    this.closingdatedate = closingdatedate;
  }

  public Vatclosing sentdatedate(DateTime sentdatedate) {
    this.sentdatedate = sentdatedate;
    return this;
  }

   /**
   * datum odeslání [persistentní položka]
   * @return sentdatedate
  **/
  @ApiModelProperty(example = "null", value = "datum odeslání [persistentní položka]")
  public DateTime getSentdatedate() {
    return sentdatedate;
  }

  public void setSentdatedate(DateTime sentdatedate) {
    this.sentdatedate = sentdatedate;
  }

  public Vatclosing vatdefinitionId(String vatdefinitionId) {
    this.vatdefinitionId = vatdefinitionId;
    return this;
  }

   /**
   * definice přiznání; id objektu definice pro dph přiznání [persistentní položka]
   * @return vatdefinitionId
  **/
  @ApiModelProperty(example = "null", value = "definice přiznání; id objektu definice pro dph přiznání [persistentní položka]")
  public String getVatdefinitionId() {
    return vatdefinitionId;
  }

  public void setVatdefinitionId(String vatdefinitionId) {
    this.vatdefinitionId = vatdefinitionId;
  }

  public Vatclosing closingtype(Integer closingtype) {
    this.closingtype = closingtype;
    return this;
  }

   /**
   * typ uzavření [persistentní položka]
   * @return closingtype
  **/
  @ApiModelProperty(example = "null", value = "typ uzavření [persistentní položka]")
  public Integer getClosingtype() {
    return closingtype;
  }

  public void setClosingtype(Integer closingtype) {
    this.closingtype = closingtype;
  }

  public Vatclosing previousclosingId(String previousclosingId) {
    this.previousclosingId = previousclosingId;
    return this;
  }

   /**
   * předchozí uzávěrka; id objektu uzávěrka dph [persistentní položka]
   * @return previousclosingId
  **/
  @ApiModelProperty(example = "null", value = "předchozí uzávěrka; id objektu uzávěrka dph [persistentní položka]")
  public String getPreviousclosingId() {
    return previousclosingId;
  }

  public void setPreviousclosingId(String previousclosingId) {
    this.previousclosingId = previousclosingId;
  }

  public Vatclosing withvatcheckreport(Boolean withvatcheckreport) {
    this.withvatcheckreport = withvatcheckreport;
    return this;
  }

   /**
   * data kv/kh dph [persistentní položka]
   * @return withvatcheckreport
  **/
  @ApiModelProperty(example = "null", value = "data kv/kh dph [persistentní položka]")
  public Boolean getWithvatcheckreport() {
    return withvatcheckreport;
  }

  public void setWithvatcheckreport(Boolean withvatcheckreport) {
    this.withvatcheckreport = withvatcheckreport;
  }

  public Vatclosing withvatreturn(Boolean withvatreturn) {
    this.withvatreturn = withvatreturn;
    return this;
  }

   /**
   * dph přiznání [persistentní položka]
   * @return withvatreturn
  **/
  @ApiModelProperty(example = "null", value = "dph přiznání [persistentní položka]")
  public Boolean getWithvatreturn() {
    return withvatreturn;
  }

  public void setWithvatreturn(Boolean withvatreturn) {
    this.withvatreturn = withvatreturn;
  }

  public Vatclosing createdbyId(String createdbyId) {
    this.createdbyId = createdbyId;
    return this;
  }

   /**
   * vytvořil; id objektu uživatel [persistentní položka]
   * @return createdbyId
  **/
  @ApiModelProperty(example = "null", value = "vytvořil; id objektu uživatel [persistentní položka]")
  public String getCreatedbyId() {
    return createdbyId;
  }

  public void setCreatedbyId(String createdbyId) {
    this.createdbyId = createdbyId;
  }

  public Vatclosing correctedbyId(String correctedbyId) {
    this.correctedbyId = correctedbyId;
    return this;
  }

   /**
   * opravil; id objektu uživatel [persistentní položka]
   * @return correctedbyId
  **/
  @ApiModelProperty(example = "null", value = "opravil; id objektu uživatel [persistentní položka]")
  public String getCorrectedbyId() {
    return correctedbyId;
  }

  public void setCorrectedbyId(String correctedbyId) {
    this.correctedbyId = correctedbyId;
  }

  public Vatclosing closingparams(byte[] closingparams) {
    this.closingparams = closingparams;
    return this;
  }

   /**
   * parametry [persistentní položka]
   * @return closingparams
  **/
  @ApiModelProperty(example = "null", value = "parametry [persistentní položka]")
  public byte[] getClosingparams() {
    return closingparams;
  }

  public void setClosingparams(byte[] closingparams) {
    this.closingparams = closingparams;
  }

  public Vatclosing vatcheckreportrows(List<Vatclosingcheckreportrow> vatcheckreportrows) {
    this.vatcheckreportrows = vatcheckreportrows;
    return this;
  }

  public Vatclosing addVatcheckreportrowsItem(Vatclosingcheckreportrow vatcheckreportrowsItem) {
    this.vatcheckreportrows.add(vatcheckreportrowsItem);
    return this;
  }

   /**
   * kv/kh dph; kolekce bo Řádek kv/kh dph [nepersistentní položka]
   * @return vatcheckreportrows
  **/
  @ApiModelProperty(example = "null", value = "kv/kh dph; kolekce bo Řádek kv/kh dph [nepersistentní položka]")
  public List<Vatclosingcheckreportrow> getVatcheckreportrows() {
    return vatcheckreportrows;
  }

  public void setVatcheckreportrows(List<Vatclosingcheckreportrow> vatcheckreportrows) {
    this.vatcheckreportrows = vatcheckreportrows;
  }

  public Vatclosing countryId(String countryId) {
    this.countryId = countryId;
    return this;
  }

   /**
   * země; id objektu země
   * @return countryId
  **/
  @ApiModelProperty(example = "null", value = "země; id objektu země")
  public String getCountryId() {
    return countryId;
  }

  public void setCountryId(String countryId) {
    this.countryId = countryId;
  }

  public Vatclosing closingperiodtypeastext(String closingperiodtypeastext) {
    this.closingperiodtypeastext = closingperiodtypeastext;
    return this;
  }

   /**
   * zdaňovací období
   * @return closingperiodtypeastext
  **/
  @ApiModelProperty(example = "null", value = "zdaňovací období")
  public String getClosingperiodtypeastext() {
    return closingperiodtypeastext;
  }

  public void setClosingperiodtypeastext(String closingperiodtypeastext) {
    this.closingperiodtypeastext = closingperiodtypeastext;
  }

  public Vatclosing closingtypeastext(String closingtypeastext) {
    this.closingtypeastext = closingtypeastext;
    return this;
  }

   /**
   * typ uzavření
   * @return closingtypeastext
  **/
  @ApiModelProperty(example = "null", value = "typ uzavření")
  public String getClosingtypeastext() {
    return closingtypeastext;
  }

  public void setClosingtypeastext(String closingtypeastext) {
    this.closingtypeastext = closingtypeastext;
  }

  public Vatclosing vatcoefficient1(Double vatcoefficient1) {
    this.vatcoefficient1 = vatcoefficient1;
    return this;
  }

   /**
   * poměrný koeficient
   * @return vatcoefficient1
  **/
  @ApiModelProperty(example = "null", value = "poměrný koeficient")
  public Double getVatcoefficient1() {
    return vatcoefficient1;
  }

  public void setVatcoefficient1(Double vatcoefficient1) {
    this.vatcoefficient1 = vatcoefficient1;
  }

  public Vatclosing vatcoefficient2(Double vatcoefficient2) {
    this.vatcoefficient2 = vatcoefficient2;
    return this;
  }

   /**
   * vypořádací koeficient
   * @return vatcoefficient2
  **/
  @ApiModelProperty(example = "null", value = "vypořádací koeficient")
  public Double getVatcoefficient2() {
    return vatcoefficient2;
  }

  public void setVatcoefficient2(Double vatcoefficient2) {
    this.vatcoefficient2 = vatcoefficient2;
  }

  public Vatclosing vatcoefficient3(Double vatcoefficient3) {
    this.vatcoefficient3 = vatcoefficient3;
    return this;
  }

   /**
   * zálohový koeficient
   * @return vatcoefficient3
  **/
  @ApiModelProperty(example = "null", value = "zálohový koeficient")
  public Double getVatcoefficient3() {
    return vatcoefficient3;
  }

  public void setVatcoefficient3(Double vatcoefficient3) {
    this.vatcoefficient3 = vatcoefficient3;
  }

  public Vatclosing mossrows(List<Vatclosingmossrow> mossrows) {
    this.mossrows = mossrows;
    return this;
  }

  public Vatclosing addMossrowsItem(Vatclosingmossrow mossrowsItem) {
    this.mossrows.add(mossrowsItem);
    return this;
  }

   /**
   * moss; kolekce bo Řádek moss dph přiznání [nepersistentní položka]
   * @return mossrows
  **/
  @ApiModelProperty(example = "null", value = "moss; kolekce bo Řádek moss dph přiznání [nepersistentní položka]")
  public List<Vatclosingmossrow> getMossrows() {
    return mossrows;
  }

  public void setMossrows(List<Vatclosingmossrow> mossrows) {
    this.mossrows = mossrows;
  }

  public Vatclosing sSfullfillconditions79(Boolean sSfullfillconditions79) {
    this.sSfullfillconditions79 = sSfullfillconditions79;
    return this;
  }

   /**
   * splnenie podmienok podľa § 79 [persistentní položka]
   * @return sSfullfillconditions79
  **/
  @ApiModelProperty(example = "null", value = "splnenie podmienok podľa § 79 [persistentní položka]")
  public Boolean getSSfullfillconditions79() {
    return sSfullfillconditions79;
  }

  public void setSSfullfillconditions79(Boolean sSfullfillconditions79) {
    this.sSfullfillconditions79 = sSfullfillconditions79;
  }

  public Vatclosing sSadviserphone(String sSadviserphone) {
    this.sSadviserphone = sSadviserphone;
    return this;
  }

   /**
   * telefón osoby [persistentní položka]
   * @return sSadviserphone
  **/
  @ApiModelProperty(example = "null", value = "telefón osoby [persistentní položka]")
  public String getSSadviserphone() {
    return sSadviserphone;
  }

  public void setSSadviserphone(String sSadviserphone) {
    this.sSadviserphone = sSadviserphone;
  }

  public Vatclosing sSadviserphonepre(String sSadviserphonepre) {
    this.sSadviserphonepre = sSadviserphonepre;
    return this;
  }

   /**
   * telefón osoby - predčislie [persistentní položka]
   * @return sSadviserphonepre
  **/
  @ApiModelProperty(example = "null", value = "telefón osoby - predčislie [persistentní položka]")
  public String getSSadviserphonepre() {
    return sSadviserphonepre;
  }

  public void setSSadviserphonepre(String sSadviserphonepre) {
    this.sSadviserphonepre = sSadviserphonepre;
  }

  public Vatclosing sSadvisername(String sSadvisername) {
    this.sSadvisername = sSadvisername;
    return this;
  }

   /**
   * meno oprávnenej osoby [persistentní položka]
   * @return sSadvisername
  **/
  @ApiModelProperty(example = "null", value = "meno oprávnenej osoby [persistentní položka]")
  public String getSSadvisername() {
    return sSadvisername;
  }

  public void setSSadvisername(String sSadvisername) {
    this.sSadvisername = sSadvisername;
  }

  public Vatclosing sSfaxnumber(String sSfaxnumber) {
    this.sSfaxnumber = sSfaxnumber;
    return this;
  }

   /**
   * Číslo faxu [persistentní položka]
   * @return sSfaxnumber
  **/
  @ApiModelProperty(example = "null", value = "Číslo faxu [persistentní položka]")
  public String getSSfaxnumber() {
    return sSfaxnumber;
  }

  public void setSSfaxnumber(String sSfaxnumber) {
    this.sSfaxnumber = sSfaxnumber;
  }

  public Vatclosing sSfaxnumberpre(String sSfaxnumberpre) {
    this.sSfaxnumberpre = sSfaxnumberpre;
    return this;
  }

   /**
   * Číslo faxu - predčíslie [persistentní položka]
   * @return sSfaxnumberpre
  **/
  @ApiModelProperty(example = "null", value = "Číslo faxu - predčíslie [persistentní položka]")
  public String getSSfaxnumberpre() {
    return sSfaxnumberpre;
  }

  public void setSSfaxnumberpre(String sSfaxnumberpre) {
    this.sSfaxnumberpre = sSfaxnumberpre;
  }

  public Vatclosing sSphonenumber(String sSphonenumber) {
    this.sSphonenumber = sSphonenumber;
    return this;
  }

   /**
   * Číslo telefónu [persistentní položka]
   * @return sSphonenumber
  **/
  @ApiModelProperty(example = "null", value = "Číslo telefónu [persistentní položka]")
  public String getSSphonenumber() {
    return sSphonenumber;
  }

  public void setSSphonenumber(String sSphonenumber) {
    this.sSphonenumber = sSphonenumber;
  }

  public Vatclosing sSphonenumberpre(String sSphonenumberpre) {
    this.sSphonenumberpre = sSphonenumberpre;
    return this;
  }

   /**
   * Číslo telefónu - predčíslie [persistentní položka]
   * @return sSphonenumberpre
  **/
  @ApiModelProperty(example = "null", value = "Číslo telefónu - predčíslie [persistentní položka]")
  public String getSSphonenumberpre() {
    return sSphonenumberpre;
  }

  public void setSSphonenumberpre(String sSphonenumberpre) {
    this.sSphonenumberpre = sSphonenumberpre;
  }

  public Vatclosing sSdateofadditional(DateTime sSdateofadditional) {
    this.sSdateofadditional = sSdateofadditional;
    return this;
  }

   /**
   * dátum zistenia [persistentní položka]
   * @return sSdateofadditional
  **/
  @ApiModelProperty(example = "null", value = "dátum zistenia [persistentní položka]")
  public DateTime getSSdateofadditional() {
    return sSdateofadditional;
  }

  public void setSSdateofadditional(DateTime sSdateofadditional) {
    this.sSdateofadditional = sSdateofadditional;
  }

  public Vatclosing sSvatpayortype(Integer sSvatpayortype) {
    this.sSvatpayortype = sSvatpayortype;
    return this;
  }

   /**
   * typ plátca [persistentní položka]
   * @return sSvatpayortype
  **/
  @ApiModelProperty(example = "null", value = "typ plátca [persistentní položka]")
  public Integer getSSvatpayortype() {
    return sSvatpayortype;
  }

  public void setSSvatpayortype(Integer sSvatpayortype) {
    this.sSvatpayortype = sSvatpayortype;
  }

  public Vatclosing sSnotax(Boolean sSnotax) {
    this.sSnotax = sSnotax;
    return this;
  }

   /**
   * nevznikla daňová povinnosť [persistentní položka]
   * @return sSnotax
  **/
  @ApiModelProperty(example = "null", value = "nevznikla daňová povinnosť [persistentní položka]")
  public Boolean getSSnotax() {
    return sSnotax;
  }

  public void setSSnotax(Boolean sSnotax) {
    this.sSnotax = sSnotax;
  }

  public Vatclosing sSfinancialbureau(String sSfinancialbureau) {
    this.sSfinancialbureau = sSfinancialbureau;
    return this;
  }

   /**
   * daňový úrad [persistentní položka]
   * @return sSfinancialbureau
  **/
  @ApiModelProperty(example = "null", value = "daňový úrad [persistentní položka]")
  public String getSSfinancialbureau() {
    return sSfinancialbureau;
  }

  public void setSSfinancialbureau(String sSfinancialbureau) {
    this.sSfinancialbureau = sSfinancialbureau;
  }

  public Vatclosing sSfirmemail(String sSfirmemail) {
    this.sSfirmemail = sSfirmemail;
    return this;
  }

   /**
   * email [persistentní položka]
   * @return sSfirmemail
  **/
  @ApiModelProperty(example = "null", value = "email [persistentní položka]")
  public String getSSfirmemail() {
    return sSfirmemail;
  }

  public void setSSfirmemail(String sSfirmemail) {
    this.sSfirmemail = sSfirmemail;
  }

  public Vatclosing sSfirmphone(String sSfirmphone) {
    this.sSfirmphone = sSfirmphone;
    return this;
  }

   /**
   * telefón [persistentní položka]
   * @return sSfirmphone
  **/
  @ApiModelProperty(example = "null", value = "telefón [persistentní položka]")
  public String getSSfirmphone() {
    return sSfirmphone;
  }

  public void setSSfirmphone(String sSfirmphone) {
    this.sSfirmphone = sSfirmphone;
  }

  public Vatclosing sFinancialbureau(String sFinancialbureau) {
    this.sFinancialbureau = sFinancialbureau;
    return this;
  }

   /**
   * fin.úřadu v, ve, pro [persistentní položka]
   * @return sFinancialbureau
  **/
  @ApiModelProperty(example = "null", value = "fin.úřadu v, ve, pro [persistentní položka]")
  public String getSFinancialbureau() {
    return sFinancialbureau;
  }

  public void setSFinancialbureau(String sFinancialbureau) {
    this.sFinancialbureau = sFinancialbureau;
  }

  public Vatclosing sNacecode(String sNacecode) {
    this.sNacecode = sNacecode;
    return this;
  }

   /**
   * Číslo převaž. činnosti (nace); id objektu nace kód [persistentní položka]
   * @return sNacecode
  **/
  @ApiModelProperty(example = "null", value = "Číslo převaž. činnosti (nace); id objektu nace kód [persistentní položka]")
  public String getSNacecode() {
    return sNacecode;
  }

  public void setSNacecode(String sNacecode) {
    this.sNacecode = sNacecode;
  }

  public Vatclosing sReasonofadditive(String sReasonofadditive) {
    this.sReasonofadditive = sReasonofadditive;
    return this;
  }

   /**
   * důvod dodatečného přiznání [persistentní položka]
   * @return sReasonofadditive
  **/
  @ApiModelProperty(example = "null", value = "důvod dodatečného přiznání [persistentní položka]")
  public String getSReasonofadditive() {
    return sReasonofadditive;
  }

  public void setSReasonofadditive(String sReasonofadditive) {
    this.sReasonofadditive = sReasonofadditive;
  }

  public Vatclosing sFosurnamea(String sFosurnamea) {
    this.sFosurnamea = sFosurnamea;
    return this;
  }

   /**
   * fyzická osoba - příjmení [persistentní položka]
   * @return sFosurnamea
  **/
  @ApiModelProperty(example = "null", value = "fyzická osoba - příjmení [persistentní položka]")
  public String getSFosurnamea() {
    return sFosurnamea;
  }

  public void setSFosurnamea(String sFosurnamea) {
    this.sFosurnamea = sFosurnamea;
  }

  public Vatclosing sAuthpersonFirstname(String sAuthpersonFirstname) {
    this.sAuthpersonFirstname = sAuthpersonFirstname;
    return this;
  }

   /**
   * jméno(-a) fo opráv. k podp. [persistentní položka]
   * @return sAuthpersonFirstname
  **/
  @ApiModelProperty(example = "null", value = "jméno(-a) fo opráv. k podp. [persistentní položka]")
  public String getSAuthpersonFirstname() {
    return sAuthpersonFirstname;
  }

  public void setSAuthpersonFirstname(String sAuthpersonFirstname) {
    this.sAuthpersonFirstname = sAuthpersonFirstname;
  }

  public Vatclosing sFinancialbureaucode(String sFinancialbureaucode) {
    this.sFinancialbureaucode = sFinancialbureaucode;
    return this;
  }

   /**
   * Číslo místně přísl. fin.úřadu [persistentní položka]
   * @return sFinancialbureaucode
  **/
  @ApiModelProperty(example = "null", value = "Číslo místně přísl. fin.úřadu [persistentní položka]")
  public String getSFinancialbureaucode() {
    return sFinancialbureaucode;
  }

  public void setSFinancialbureaucode(String sFinancialbureaucode) {
    this.sFinancialbureaucode = sFinancialbureaucode;
  }

  public Vatclosing sNumofattachments(Integer sNumofattachments) {
    this.sNumofattachments = sNumofattachments;
    return this;
  }

   /**
   * počet příloh [persistentní položka]
   * @return sNumofattachments
  **/
  @ApiModelProperty(example = "null", value = "počet příloh [persistentní položka]")
  public Integer getSNumofattachments() {
    return sNumofattachments;
  }

  public void setSNumofattachments(Integer sNumofattachments) {
    this.sNumofattachments = sNumofattachments;
  }

  public Vatclosing sVatpayortype(Integer sVatpayortype) {
    this.sVatpayortype = sVatpayortype;
    return this;
  }

   /**
   * typ plátce [persistentní položka]
   * @return sVatpayortype
  **/
  @ApiModelProperty(example = "null", value = "typ plátce [persistentní položka]")
  public Integer getSVatpayortype() {
    return sVatpayortype;
  }

  public void setSVatpayortype(Integer sVatpayortype) {
    this.sVatpayortype = sVatpayortype;
  }

  public Vatclosing sFofirstnamea(String sFofirstnamea) {
    this.sFofirstnamea = sFofirstnamea;
    return this;
  }

   /**
   * fyzická osoba - jméno [persistentní položka]
   * @return sFofirstnamea
  **/
  @ApiModelProperty(example = "null", value = "fyzická osoba - jméno [persistentní položka]")
  public String getSFofirstnamea() {
    return sFofirstnamea;
  }

  public void setSFofirstnamea(String sFofirstnamea) {
    this.sFofirstnamea = sFofirstnamea;
  }

  public Vatclosing sAuthpersonSurname(String sAuthpersonSurname) {
    this.sAuthpersonSurname = sAuthpersonSurname;
    return this;
  }

   /**
   * příjmení fo opráv. k podp. [persistentní položka]
   * @return sAuthpersonSurname
  **/
  @ApiModelProperty(example = "null", value = "příjmení fo opráv. k podp. [persistentní položka]")
  public String getSAuthpersonSurname() {
    return sAuthpersonSurname;
  }

  public void setSAuthpersonSurname(String sAuthpersonSurname) {
    this.sAuthpersonSurname = sAuthpersonSurname;
  }

  public Vatclosing sAdvisercode(Integer sAdvisercode) {
    this.sAdvisercode = sAdvisercode;
    return this;
  }

   /**
   * volba typu zástupce [persistentní položka]
   * @return sAdvisercode
  **/
  @ApiModelProperty(example = "null", value = "volba typu zástupce [persistentní položka]")
  public Integer getSAdvisercode() {
    return sAdvisercode;
  }

  public void setSAdvisercode(Integer sAdvisercode) {
    this.sAdvisercode = sAdvisercode;
  }

  public Vatclosing sRegionaloffice(String sRegionaloffice) {
    this.sRegionaloffice = sRegionaloffice;
    return this;
  }

   /**
   * Územní pracoviště v, ve, pro [persistentní položka]
   * @return sRegionaloffice
  **/
  @ApiModelProperty(example = "null", value = "Územní pracoviště v, ve, pro [persistentní položka]")
  public String getSRegionaloffice() {
    return sRegionaloffice;
  }

  public void setSRegionaloffice(String sRegionaloffice) {
    this.sRegionaloffice = sRegionaloffice;
  }

  public Vatclosing sNumofsheets(Integer sNumofsheets) {
    this.sNumofsheets = sNumofsheets;
    return this;
  }

   /**
   * počet listů [persistentní položka]
   * @return sNumofsheets
  **/
  @ApiModelProperty(example = "null", value = "počet listů [persistentní položka]")
  public Integer getSNumofsheets() {
    return sNumofsheets;
  }

  public void setSNumofsheets(Integer sNumofsheets) {
    this.sNumofsheets = sNumofsheets;
  }

  public Vatclosing sNoitemsforcsection(Boolean sNoitemsforcsection) {
    this.sNoitemsforcsection = sNoitemsforcsection;
    return this;
  }

   /**
   * pro c. oddÍl neexist.údaje [persistentní položka]
   * @return sNoitemsforcsection
  **/
  @ApiModelProperty(example = "null", value = "pro c. oddÍl neexist.údaje [persistentní položka]")
  public Boolean getSNoitemsforcsection() {
    return sNoitemsforcsection;
  }

  public void setSNoitemsforcsection(Boolean sNoitemsforcsection) {
    this.sNoitemsforcsection = sNoitemsforcsection;
  }

  public Vatclosing sFotitlea(String sFotitlea) {
    this.sFotitlea = sFotitlea;
    return this;
  }

   /**
   * fyzická osoba - titul [persistentní položka]
   * @return sFotitlea
  **/
  @ApiModelProperty(example = "null", value = "fyzická osoba - titul [persistentní položka]")
  public String getSFotitlea() {
    return sFotitlea;
  }

  public void setSFotitlea(String sFotitlea) {
    this.sFotitlea = sFotitlea;
  }

  public Vatclosing sAssemblyperson(String sAssemblyperson) {
    this.sAssemblyperson = sAssemblyperson;
    return this;
  }

   /**
   * přiznání sestavil [persistentní položka]
   * @return sAssemblyperson
  **/
  @ApiModelProperty(example = "null", value = "přiznání sestavil [persistentní položka]")
  public String getSAssemblyperson() {
    return sAssemblyperson;
  }

  public void setSAssemblyperson(String sAssemblyperson) {
    this.sAssemblyperson = sAssemblyperson;
  }

  public Vatclosing sAdvisertype(Integer sAdvisertype) {
    this.sAdvisertype = sAdvisertype;
    return this;
  }

   /**
   * typ zástupce [persistentní položka]
   * @return sAdvisertype
  **/
  @ApiModelProperty(example = "null", value = "typ zástupce [persistentní položka]")
  public Integer getSAdvisertype() {
    return sAdvisertype;
  }

  public void setSAdvisertype(Integer sAdvisertype) {
    this.sAdvisertype = sAdvisertype;
  }

  public Vatclosing sAuthpersonStatus(String sAuthpersonStatus) {
    this.sAuthpersonStatus = sAuthpersonStatus;
    return this;
  }

   /**
   * vztah k práv. osobě [persistentní položka]
   * @return sAuthpersonStatus
  **/
  @ApiModelProperty(example = "null", value = "vztah k práv. osobě [persistentní položka]")
  public String getSAuthpersonStatus() {
    return sAuthpersonStatus;
  }

  public void setSAuthpersonStatus(String sAuthpersonStatus) {
    this.sAuthpersonStatus = sAuthpersonStatus;
  }

  public Vatclosing sRegionalofficecode(String sRegionalofficecode) {
    this.sRegionalofficecode = sRegionalofficecode;
    return this;
  }

   /**
   * Číslo územního pracoviště [persistentní položka]
   * @return sRegionalofficecode
  **/
  @ApiModelProperty(example = "null", value = "Číslo územního pracoviště [persistentní položka]")
  public String getSRegionalofficecode() {
    return sRegionalofficecode;
  }

  public void setSRegionalofficecode(String sRegionalofficecode) {
    this.sRegionalofficecode = sRegionalofficecode;
  }

  public Vatclosing sNextyeartaxperiodcode(Integer sNextyeartaxperiodcode) {
    this.sNextyeartaxperiodcode = sNextyeartaxperiodcode;
    return this;
  }

   /**
   * kód zdaň.období násl. roku [persistentní položka]
   * @return sNextyeartaxperiodcode
  **/
  @ApiModelProperty(example = "null", value = "kód zdaň.období násl. roku [persistentní položka]")
  public Integer getSNextyeartaxperiodcode() {
    return sNextyeartaxperiodcode;
  }

  public void setSNextyeartaxperiodcode(Integer sNextyeartaxperiodcode) {
    this.sNextyeartaxperiodcode = sNextyeartaxperiodcode;
  }

  public Vatclosing sIdentnumber(String sIdentnumber) {
    this.sIdentnumber = sIdentnumber;
    return this;
  }

   /**
   * rodné číslo [persistentní položka]
   * @return sIdentnumber
  **/
  @ApiModelProperty(example = "null", value = "rodné číslo [persistentní položka]")
  public String getSIdentnumber() {
    return sIdentnumber;
  }

  public void setSIdentnumber(String sIdentnumber) {
    this.sIdentnumber = sIdentnumber;
  }

  public Vatclosing sAssemblytelephone(String sAssemblytelephone) {
    this.sAssemblytelephone = sAssemblytelephone;
    return this;
  }

   /**
   * telefon [persistentní položka]
   * @return sAssemblytelephone
  **/
  @ApiModelProperty(example = "null", value = "telefon [persistentní položka]")
  public String getSAssemblytelephone() {
    return sAssemblytelephone;
  }

  public void setSAssemblytelephone(String sAssemblytelephone) {
    this.sAssemblytelephone = sAssemblytelephone;
  }

  public Vatclosing sAdviserfirstname(String sAdviserfirstname) {
    this.sAdviserfirstname = sAdviserfirstname;
    return this;
  }

   /**
   * jméno zástupce [persistentní položka]
   * @return sAdviserfirstname
  **/
  @ApiModelProperty(example = "null", value = "jméno zástupce [persistentní položka]")
  public String getSAdviserfirstname() {
    return sAdviserfirstname;
  }

  public void setSAdviserfirstname(String sAdviserfirstname) {
    this.sAdviserfirstname = sAdviserfirstname;
  }

  public Vatclosing sCompanytype(Integer sCompanytype) {
    this.sCompanytype = sCompanytype;
    return this;
  }

   /**
   * právní forma [persistentní položka]
   * @return sCompanytype
  **/
  @ApiModelProperty(example = "null", value = "právní forma [persistentní položka]")
  public Integer getSCompanytype() {
    return sCompanytype;
  }

  public void setSCompanytype(Integer sCompanytype) {
    this.sCompanytype = sCompanytype;
  }

  public Vatclosing sInsolventperiod(Boolean sInsolventperiod) {
    this.sInsolventperiod = sInsolventperiod;
    return this;
  }

   /**
   * zaháj./ukonč. insolvent.řízení [persistentní položka]
   * @return sInsolventperiod
  **/
  @ApiModelProperty(example = "null", value = "zaháj./ukonč. insolvent.řízení [persistentní položka]")
  public Boolean getSInsolventperiod() {
    return sInsolventperiod;
  }

  public void setSInsolventperiod(Boolean sInsolventperiod) {
    this.sInsolventperiod = sInsolventperiod;
  }

  public Vatclosing sAdvisersurname(String sAdvisersurname) {
    this.sAdvisersurname = sAdvisersurname;
    return this;
  }

   /**
   * příjmení zástupce [persistentní položka]
   * @return sAdvisersurname
  **/
  @ApiModelProperty(example = "null", value = "příjmení zástupce [persistentní položka]")
  public String getSAdvisersurname() {
    return sAdvisersurname;
  }

  public void setSAdvisersurname(String sAdvisersurname) {
    this.sAdvisersurname = sAdvisersurname;
  }

  public Vatclosing sInsolventperiodfrom(DateTime sInsolventperiodfrom) {
    this.sInsolventperiodfrom = sInsolventperiodfrom;
    return this;
  }

   /**
   * datum zahájení ins.řízení [persistentní položka]
   * @return sInsolventperiodfrom
  **/
  @ApiModelProperty(example = "null", value = "datum zahájení ins.řízení [persistentní položka]")
  public DateTime getSInsolventperiodfrom() {
    return sInsolventperiodfrom;
  }

  public void setSInsolventperiodfrom(DateTime sInsolventperiodfrom) {
    this.sInsolventperiodfrom = sInsolventperiodfrom;
  }

  public Vatclosing sAdvisertitle(String sAdvisertitle) {
    this.sAdvisertitle = sAdvisertitle;
    return this;
  }

   /**
   * název právnické osoby [persistentní položka]
   * @return sAdvisertitle
  **/
  @ApiModelProperty(example = "null", value = "název právnické osoby [persistentní položka]")
  public String getSAdvisertitle() {
    return sAdvisertitle;
  }

  public void setSAdvisertitle(String sAdvisertitle) {
    this.sAdvisertitle = sAdvisertitle;
  }

  public Vatclosing sInsolventperiodto(DateTime sInsolventperiodto) {
    this.sInsolventperiodto = sInsolventperiodto;
    return this;
  }

   /**
   * datum ukonč. ins. řízení [persistentní položka]
   * @return sInsolventperiodto
  **/
  @ApiModelProperty(example = "null", value = "datum ukonč. ins. řízení [persistentní položka]")
  public DateTime getSInsolventperiodto() {
    return sInsolventperiodto;
  }

  public void setSInsolventperiodto(DateTime sInsolventperiodto) {
    this.sInsolventperiodto = sInsolventperiodto;
  }

  public Vatclosing sAdviserbirthdate(DateTime sAdviserbirthdate) {
    this.sAdviserbirthdate = sAdviserbirthdate;
    return this;
  }

   /**
   * datum narození zástupce [persistentní položka]
   * @return sAdviserbirthdate
  **/
  @ApiModelProperty(example = "null", value = "datum narození zástupce [persistentní položka]")
  public DateTime getSAdviserbirthdate() {
    return sAdviserbirthdate;
  }

  public void setSAdviserbirthdate(DateTime sAdviserbirthdate) {
    this.sAdviserbirthdate = sAdviserbirthdate;
  }

  public Vatclosing sAdviserevnum(String sAdviserevnum) {
    this.sAdviserevnum = sAdviserevnum;
    return this;
  }

   /**
   * evid.číslo osvědčení daň. por. [persistentní položka]
   * @return sAdviserevnum
  **/
  @ApiModelProperty(example = "null", value = "evid.číslo osvědčení daň. por. [persistentní položka]")
  public String getSAdviserevnum() {
    return sAdviserevnum;
  }

  public void setSAdviserevnum(String sAdviserevnum) {
    this.sAdviserevnum = sAdviserevnum;
  }

  public Vatclosing sAdviseric(String sAdviseric) {
    this.sAdviseric = sAdviseric;
    return this;
  }

   /**
   * iČ právnické osoby [persistentní položka]
   * @return sAdviseric
  **/
  @ApiModelProperty(example = "null", value = "iČ právnické osoby [persistentní položka]")
  public String getSAdviseric() {
    return sAdviseric;
  }

  public void setSAdviseric(String sAdviseric) {
    this.sAdviseric = sAdviseric;
  }

  public Vatclosing sAssemblyemail(String sAssemblyemail) {
    this.sAssemblyemail = sAssemblyemail;
    return this;
  }

   /**
   * email [persistentní položka]
   * @return sAssemblyemail
  **/
  @ApiModelProperty(example = "null", value = "email [persistentní položka]")
  public String getSAssemblyemail() {
    return sAssemblyemail;
  }

  public void setSAssemblyemail(String sAssemblyemail) {
    this.sAssemblyemail = sAssemblyemail;
  }

  public Vatclosing sAssemblydate(DateTime sAssemblydate) {
    this.sAssemblydate = sAssemblydate;
    return this;
  }

   /**
   * datum přiznání [persistentní položka]
   * @return sAssemblydate
  **/
  @ApiModelProperty(example = "null", value = "datum přiznání [persistentní položka]")
  public DateTime getSAssemblydate() {
    return sAssemblydate;
  }

  public void setSAssemblydate(DateTime sAssemblydate) {
    this.sAssemblydate = sAssemblydate;
  }

  public Vatclosing sDateofadditive(DateTime sDateofadditive) {
    this.sDateofadditive = sDateofadditive;
    return this;
  }

   /**
   * důvody pro ddp zjištěny dne [persistentní položka]
   * @return sDateofadditive
  **/
  @ApiModelProperty(example = "null", value = "důvody pro ddp zjištěny dne [persistentní položka]")
  public DateTime getSDateofadditive() {
    return sDateofadditive;
  }

  public void setSDateofadditive(DateTime sDateofadditive) {
    this.sDateofadditive = sDateofadditive;
  }

  public Vatclosing sNotax(Boolean sNotax) {
    this.sNotax = sNotax;
    return this;
  }

   /**
   * nevznikla daňová povinnost [persistentní položka]
   * @return sNotax
  **/
  @ApiModelProperty(example = "null", value = "nevznikla daňová povinnost [persistentní položka]")
  public Boolean getSNotax() {
    return sNotax;
  }

  public void setSNotax(Boolean sNotax) {
    this.sNotax = sNotax;
  }

  public Vatclosing sIban(String sIban) {
    this.sIban = sIban;
    return this;
  }

   /**
   * iban [persistentní položka]
   * @return sIban
  **/
  @ApiModelProperty(example = "null", value = "iban [persistentní položka]")
  public String getSIban() {
    return sIban;
  }

  public void setSIban(String sIban) {
    this.sIban = sIban;
  }

  public Vatclosing sBic(String sBic) {
    this.sBic = sBic;
    return this;
  }

   /**
   * bic [persistentní položka]
   * @return sBic
  **/
  @ApiModelProperty(example = "null", value = "bic [persistentní položka]")
  public String getSBic() {
    return sBic;
  }

  public void setSBic(String sBic) {
    this.sBic = sBic;
  }

  public Vatclosing sMossrefnumber(String sMossrefnumber) {
    this.sMossrefnumber = sMossrefnumber;
    return this;
  }

   /**
   * referenční číslo přiznání [persistentní položka]
   * @return sMossrefnumber
  **/
  @ApiModelProperty(example = "null", value = "referenční číslo přiznání [persistentní položka]")
  public String getSMossrefnumber() {
    return sMossrefnumber;
  }

  public void setSMossrefnumber(String sMossrefnumber) {
    this.sMossrefnumber = sMossrefnumber;
  }

  public Vatclosing sMossaccountname(String sMossaccountname) {
    this.sMossaccountname = sMossaccountname;
    return this;
  }

   /**
   * jméno majitele bankovního účtu [persistentní položka]
   * @return sMossaccountname
  **/
  @ApiModelProperty(example = "null", value = "jméno majitele bankovního účtu [persistentní položka]")
  public String getSMossaccountname() {
    return sMossaccountname;
  }

  public void setSMossaccountname(String sMossaccountname) {
    this.sMossaccountname = sMossaccountname;
  }

  public Vatclosing sKhdphAppealrefnumber(String sKhdphAppealrefnumber) {
    this.sKhdphAppealrefnumber = sKhdphAppealrefnumber;
    return this;
  }

   /**
   * Číslo jednací výzvy: [persistentní položka]
   * @return sKhdphAppealrefnumber
  **/
  @ApiModelProperty(example = "null", value = "Číslo jednací výzvy: [persistentní položka]")
  public String getSKhdphAppealrefnumber() {
    return sKhdphAppealrefnumber;
  }

  public void setSKhdphAppealrefnumber(String sKhdphAppealrefnumber) {
    this.sKhdphAppealrefnumber = sKhdphAppealrefnumber;
  }

  public Vatclosing sKhdphAppealreply(Integer sKhdphAppealreply) {
    this.sKhdphAppealreply = sKhdphAppealreply;
    return this;
  }

   /**
   * rychlá odpověď na výzvu: [persistentní položka]
   * @return sKhdphAppealreply
  **/
  @ApiModelProperty(example = "null", value = "rychlá odpověď na výzvu: [persistentní položka]")
  public Integer getSKhdphAppealreply() {
    return sKhdphAppealreply;
  }

  public void setSKhdphAppealreply(Integer sKhdphAppealreply) {
    this.sKhdphAppealreply = sKhdphAppealreply;
  }

  public Vatclosing sKhdphCorrectiondate(DateTime sKhdphCorrectiondate) {
    this.sKhdphCorrectiondate = sKhdphCorrectiondate;
    return this;
  }

   /**
   * následné hlášení k datu: [persistentní položka]
   * @return sKhdphCorrectiondate
  **/
  @ApiModelProperty(example = "null", value = "následné hlášení k datu: [persistentní položka]")
  public DateTime getSKhdphCorrectiondate() {
    return sKhdphCorrectiondate;
  }

  public void setSKhdphCorrectiondate(DateTime sKhdphCorrectiondate) {
    this.sKhdphCorrectiondate = sKhdphCorrectiondate;
  }

  public Vatclosing sKhdphType(Integer sKhdphType) {
    this.sKhdphType = sKhdphType;
    return this;
  }

   /**
   * druh kontrolního hlášení: [persistentní položka]
   * @return sKhdphType
  **/
  @ApiModelProperty(example = "null", value = "druh kontrolního hlášení: [persistentní položka]")
  public Integer getSKhdphType() {
    return sKhdphType;
  }

  public void setSKhdphType(Integer sKhdphType) {
    this.sKhdphType = sKhdphType;
  }

  public Vatclosing sDataboxid(String sDataboxid) {
    this.sDataboxid = sDataboxid;
    return this;
  }

   /**
   * identifikátor datové schránky [persistentní položka]
   * @return sDataboxid
  **/
  @ApiModelProperty(example = "null", value = "identifikátor datové schránky [persistentní položka]")
  public String getSDataboxid() {
    return sDataboxid;
  }

  public void setSDataboxid(String sDataboxid) {
    this.sDataboxid = sDataboxid;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Vatclosing vatclosing = (Vatclosing) o;
    return Objects.equals(this.displayname, vatclosing.displayname) &&
        Objects.equals(this.id, vatclosing.id) &&
        Objects.equals(this.classid, vatclosing.classid) &&
        Objects.equals(this.objversion, vatclosing.objversion) &&
        Objects.equals(this.rows, vatclosing.rows) &&
        Objects.equals(this.description, vatclosing.description) &&
        Objects.equals(this.closingperiodtype, vatclosing.closingperiodtype) &&
        Objects.equals(this.datefromdate, vatclosing.datefromdate) &&
        Objects.equals(this.datetodate, vatclosing.datetodate) &&
        Objects.equals(this.closingdatedate, vatclosing.closingdatedate) &&
        Objects.equals(this.sentdatedate, vatclosing.sentdatedate) &&
        Objects.equals(this.vatdefinitionId, vatclosing.vatdefinitionId) &&
        Objects.equals(this.closingtype, vatclosing.closingtype) &&
        Objects.equals(this.previousclosingId, vatclosing.previousclosingId) &&
        Objects.equals(this.withvatcheckreport, vatclosing.withvatcheckreport) &&
        Objects.equals(this.withvatreturn, vatclosing.withvatreturn) &&
        Objects.equals(this.createdbyId, vatclosing.createdbyId) &&
        Objects.equals(this.correctedbyId, vatclosing.correctedbyId) &&
        Objects.equals(this.closingparams, vatclosing.closingparams) &&
        Objects.equals(this.vatcheckreportrows, vatclosing.vatcheckreportrows) &&
        Objects.equals(this.countryId, vatclosing.countryId) &&
        Objects.equals(this.closingperiodtypeastext, vatclosing.closingperiodtypeastext) &&
        Objects.equals(this.closingtypeastext, vatclosing.closingtypeastext) &&
        Objects.equals(this.vatcoefficient1, vatclosing.vatcoefficient1) &&
        Objects.equals(this.vatcoefficient2, vatclosing.vatcoefficient2) &&
        Objects.equals(this.vatcoefficient3, vatclosing.vatcoefficient3) &&
        Objects.equals(this.mossrows, vatclosing.mossrows) &&
        Objects.equals(this.sSfullfillconditions79, vatclosing.sSfullfillconditions79) &&
        Objects.equals(this.sSadviserphone, vatclosing.sSadviserphone) &&
        Objects.equals(this.sSadviserphonepre, vatclosing.sSadviserphonepre) &&
        Objects.equals(this.sSadvisername, vatclosing.sSadvisername) &&
        Objects.equals(this.sSfaxnumber, vatclosing.sSfaxnumber) &&
        Objects.equals(this.sSfaxnumberpre, vatclosing.sSfaxnumberpre) &&
        Objects.equals(this.sSphonenumber, vatclosing.sSphonenumber) &&
        Objects.equals(this.sSphonenumberpre, vatclosing.sSphonenumberpre) &&
        Objects.equals(this.sSdateofadditional, vatclosing.sSdateofadditional) &&
        Objects.equals(this.sSvatpayortype, vatclosing.sSvatpayortype) &&
        Objects.equals(this.sSnotax, vatclosing.sSnotax) &&
        Objects.equals(this.sSfinancialbureau, vatclosing.sSfinancialbureau) &&
        Objects.equals(this.sSfirmemail, vatclosing.sSfirmemail) &&
        Objects.equals(this.sSfirmphone, vatclosing.sSfirmphone) &&
        Objects.equals(this.sFinancialbureau, vatclosing.sFinancialbureau) &&
        Objects.equals(this.sNacecode, vatclosing.sNacecode) &&
        Objects.equals(this.sReasonofadditive, vatclosing.sReasonofadditive) &&
        Objects.equals(this.sFosurnamea, vatclosing.sFosurnamea) &&
        Objects.equals(this.sAuthpersonFirstname, vatclosing.sAuthpersonFirstname) &&
        Objects.equals(this.sFinancialbureaucode, vatclosing.sFinancialbureaucode) &&
        Objects.equals(this.sNumofattachments, vatclosing.sNumofattachments) &&
        Objects.equals(this.sVatpayortype, vatclosing.sVatpayortype) &&
        Objects.equals(this.sFofirstnamea, vatclosing.sFofirstnamea) &&
        Objects.equals(this.sAuthpersonSurname, vatclosing.sAuthpersonSurname) &&
        Objects.equals(this.sAdvisercode, vatclosing.sAdvisercode) &&
        Objects.equals(this.sRegionaloffice, vatclosing.sRegionaloffice) &&
        Objects.equals(this.sNumofsheets, vatclosing.sNumofsheets) &&
        Objects.equals(this.sNoitemsforcsection, vatclosing.sNoitemsforcsection) &&
        Objects.equals(this.sFotitlea, vatclosing.sFotitlea) &&
        Objects.equals(this.sAssemblyperson, vatclosing.sAssemblyperson) &&
        Objects.equals(this.sAdvisertype, vatclosing.sAdvisertype) &&
        Objects.equals(this.sAuthpersonStatus, vatclosing.sAuthpersonStatus) &&
        Objects.equals(this.sRegionalofficecode, vatclosing.sRegionalofficecode) &&
        Objects.equals(this.sNextyeartaxperiodcode, vatclosing.sNextyeartaxperiodcode) &&
        Objects.equals(this.sIdentnumber, vatclosing.sIdentnumber) &&
        Objects.equals(this.sAssemblytelephone, vatclosing.sAssemblytelephone) &&
        Objects.equals(this.sAdviserfirstname, vatclosing.sAdviserfirstname) &&
        Objects.equals(this.sCompanytype, vatclosing.sCompanytype) &&
        Objects.equals(this.sInsolventperiod, vatclosing.sInsolventperiod) &&
        Objects.equals(this.sAdvisersurname, vatclosing.sAdvisersurname) &&
        Objects.equals(this.sInsolventperiodfrom, vatclosing.sInsolventperiodfrom) &&
        Objects.equals(this.sAdvisertitle, vatclosing.sAdvisertitle) &&
        Objects.equals(this.sInsolventperiodto, vatclosing.sInsolventperiodto) &&
        Objects.equals(this.sAdviserbirthdate, vatclosing.sAdviserbirthdate) &&
        Objects.equals(this.sAdviserevnum, vatclosing.sAdviserevnum) &&
        Objects.equals(this.sAdviseric, vatclosing.sAdviseric) &&
        Objects.equals(this.sAssemblyemail, vatclosing.sAssemblyemail) &&
        Objects.equals(this.sAssemblydate, vatclosing.sAssemblydate) &&
        Objects.equals(this.sDateofadditive, vatclosing.sDateofadditive) &&
        Objects.equals(this.sNotax, vatclosing.sNotax) &&
        Objects.equals(this.sIban, vatclosing.sIban) &&
        Objects.equals(this.sBic, vatclosing.sBic) &&
        Objects.equals(this.sMossrefnumber, vatclosing.sMossrefnumber) &&
        Objects.equals(this.sMossaccountname, vatclosing.sMossaccountname) &&
        Objects.equals(this.sKhdphAppealrefnumber, vatclosing.sKhdphAppealrefnumber) &&
        Objects.equals(this.sKhdphAppealreply, vatclosing.sKhdphAppealreply) &&
        Objects.equals(this.sKhdphCorrectiondate, vatclosing.sKhdphCorrectiondate) &&
        Objects.equals(this.sKhdphType, vatclosing.sKhdphType) &&
        Objects.equals(this.sDataboxid, vatclosing.sDataboxid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(displayname, id, classid, objversion, rows, description, closingperiodtype, datefromdate, datetodate, closingdatedate, sentdatedate, vatdefinitionId, closingtype, previousclosingId, withvatcheckreport, withvatreturn, createdbyId, correctedbyId, closingparams, vatcheckreportrows, countryId, closingperiodtypeastext, closingtypeastext, vatcoefficient1, vatcoefficient2, vatcoefficient3, mossrows, sSfullfillconditions79, sSadviserphone, sSadviserphonepre, sSadvisername, sSfaxnumber, sSfaxnumberpre, sSphonenumber, sSphonenumberpre, sSdateofadditional, sSvatpayortype, sSnotax, sSfinancialbureau, sSfirmemail, sSfirmphone, sFinancialbureau, sNacecode, sReasonofadditive, sFosurnamea, sAuthpersonFirstname, sFinancialbureaucode, sNumofattachments, sVatpayortype, sFofirstnamea, sAuthpersonSurname, sAdvisercode, sRegionaloffice, sNumofsheets, sNoitemsforcsection, sFotitlea, sAssemblyperson, sAdvisertype, sAuthpersonStatus, sRegionalofficecode, sNextyeartaxperiodcode, sIdentnumber, sAssemblytelephone, sAdviserfirstname, sCompanytype, sInsolventperiod, sAdvisersurname, sInsolventperiodfrom, sAdvisertitle, sInsolventperiodto, sAdviserbirthdate, sAdviserevnum, sAdviseric, sAssemblyemail, sAssemblydate, sDateofadditive, sNotax, sIban, sBic, sMossrefnumber, sMossaccountname, sKhdphAppealrefnumber, sKhdphAppealreply, sKhdphCorrectiondate, sKhdphType, sDataboxid);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Vatclosing {\n");
    
    sb.append("    displayname: ").append(toIndentedString(displayname)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    classid: ").append(toIndentedString(classid)).append("\n");
    sb.append("    objversion: ").append(toIndentedString(objversion)).append("\n");
    sb.append("    rows: ").append(toIndentedString(rows)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    closingperiodtype: ").append(toIndentedString(closingperiodtype)).append("\n");
    sb.append("    datefromdate: ").append(toIndentedString(datefromdate)).append("\n");
    sb.append("    datetodate: ").append(toIndentedString(datetodate)).append("\n");
    sb.append("    closingdatedate: ").append(toIndentedString(closingdatedate)).append("\n");
    sb.append("    sentdatedate: ").append(toIndentedString(sentdatedate)).append("\n");
    sb.append("    vatdefinitionId: ").append(toIndentedString(vatdefinitionId)).append("\n");
    sb.append("    closingtype: ").append(toIndentedString(closingtype)).append("\n");
    sb.append("    previousclosingId: ").append(toIndentedString(previousclosingId)).append("\n");
    sb.append("    withvatcheckreport: ").append(toIndentedString(withvatcheckreport)).append("\n");
    sb.append("    withvatreturn: ").append(toIndentedString(withvatreturn)).append("\n");
    sb.append("    createdbyId: ").append(toIndentedString(createdbyId)).append("\n");
    sb.append("    correctedbyId: ").append(toIndentedString(correctedbyId)).append("\n");
    sb.append("    closingparams: ").append(toIndentedString(closingparams)).append("\n");
    sb.append("    vatcheckreportrows: ").append(toIndentedString(vatcheckreportrows)).append("\n");
    sb.append("    countryId: ").append(toIndentedString(countryId)).append("\n");
    sb.append("    closingperiodtypeastext: ").append(toIndentedString(closingperiodtypeastext)).append("\n");
    sb.append("    closingtypeastext: ").append(toIndentedString(closingtypeastext)).append("\n");
    sb.append("    vatcoefficient1: ").append(toIndentedString(vatcoefficient1)).append("\n");
    sb.append("    vatcoefficient2: ").append(toIndentedString(vatcoefficient2)).append("\n");
    sb.append("    vatcoefficient3: ").append(toIndentedString(vatcoefficient3)).append("\n");
    sb.append("    mossrows: ").append(toIndentedString(mossrows)).append("\n");
    sb.append("    sSfullfillconditions79: ").append(toIndentedString(sSfullfillconditions79)).append("\n");
    sb.append("    sSadviserphone: ").append(toIndentedString(sSadviserphone)).append("\n");
    sb.append("    sSadviserphonepre: ").append(toIndentedString(sSadviserphonepre)).append("\n");
    sb.append("    sSadvisername: ").append(toIndentedString(sSadvisername)).append("\n");
    sb.append("    sSfaxnumber: ").append(toIndentedString(sSfaxnumber)).append("\n");
    sb.append("    sSfaxnumberpre: ").append(toIndentedString(sSfaxnumberpre)).append("\n");
    sb.append("    sSphonenumber: ").append(toIndentedString(sSphonenumber)).append("\n");
    sb.append("    sSphonenumberpre: ").append(toIndentedString(sSphonenumberpre)).append("\n");
    sb.append("    sSdateofadditional: ").append(toIndentedString(sSdateofadditional)).append("\n");
    sb.append("    sSvatpayortype: ").append(toIndentedString(sSvatpayortype)).append("\n");
    sb.append("    sSnotax: ").append(toIndentedString(sSnotax)).append("\n");
    sb.append("    sSfinancialbureau: ").append(toIndentedString(sSfinancialbureau)).append("\n");
    sb.append("    sSfirmemail: ").append(toIndentedString(sSfirmemail)).append("\n");
    sb.append("    sSfirmphone: ").append(toIndentedString(sSfirmphone)).append("\n");
    sb.append("    sFinancialbureau: ").append(toIndentedString(sFinancialbureau)).append("\n");
    sb.append("    sNacecode: ").append(toIndentedString(sNacecode)).append("\n");
    sb.append("    sReasonofadditive: ").append(toIndentedString(sReasonofadditive)).append("\n");
    sb.append("    sFosurnamea: ").append(toIndentedString(sFosurnamea)).append("\n");
    sb.append("    sAuthpersonFirstname: ").append(toIndentedString(sAuthpersonFirstname)).append("\n");
    sb.append("    sFinancialbureaucode: ").append(toIndentedString(sFinancialbureaucode)).append("\n");
    sb.append("    sNumofattachments: ").append(toIndentedString(sNumofattachments)).append("\n");
    sb.append("    sVatpayortype: ").append(toIndentedString(sVatpayortype)).append("\n");
    sb.append("    sFofirstnamea: ").append(toIndentedString(sFofirstnamea)).append("\n");
    sb.append("    sAuthpersonSurname: ").append(toIndentedString(sAuthpersonSurname)).append("\n");
    sb.append("    sAdvisercode: ").append(toIndentedString(sAdvisercode)).append("\n");
    sb.append("    sRegionaloffice: ").append(toIndentedString(sRegionaloffice)).append("\n");
    sb.append("    sNumofsheets: ").append(toIndentedString(sNumofsheets)).append("\n");
    sb.append("    sNoitemsforcsection: ").append(toIndentedString(sNoitemsforcsection)).append("\n");
    sb.append("    sFotitlea: ").append(toIndentedString(sFotitlea)).append("\n");
    sb.append("    sAssemblyperson: ").append(toIndentedString(sAssemblyperson)).append("\n");
    sb.append("    sAdvisertype: ").append(toIndentedString(sAdvisertype)).append("\n");
    sb.append("    sAuthpersonStatus: ").append(toIndentedString(sAuthpersonStatus)).append("\n");
    sb.append("    sRegionalofficecode: ").append(toIndentedString(sRegionalofficecode)).append("\n");
    sb.append("    sNextyeartaxperiodcode: ").append(toIndentedString(sNextyeartaxperiodcode)).append("\n");
    sb.append("    sIdentnumber: ").append(toIndentedString(sIdentnumber)).append("\n");
    sb.append("    sAssemblytelephone: ").append(toIndentedString(sAssemblytelephone)).append("\n");
    sb.append("    sAdviserfirstname: ").append(toIndentedString(sAdviserfirstname)).append("\n");
    sb.append("    sCompanytype: ").append(toIndentedString(sCompanytype)).append("\n");
    sb.append("    sInsolventperiod: ").append(toIndentedString(sInsolventperiod)).append("\n");
    sb.append("    sAdvisersurname: ").append(toIndentedString(sAdvisersurname)).append("\n");
    sb.append("    sInsolventperiodfrom: ").append(toIndentedString(sInsolventperiodfrom)).append("\n");
    sb.append("    sAdvisertitle: ").append(toIndentedString(sAdvisertitle)).append("\n");
    sb.append("    sInsolventperiodto: ").append(toIndentedString(sInsolventperiodto)).append("\n");
    sb.append("    sAdviserbirthdate: ").append(toIndentedString(sAdviserbirthdate)).append("\n");
    sb.append("    sAdviserevnum: ").append(toIndentedString(sAdviserevnum)).append("\n");
    sb.append("    sAdviseric: ").append(toIndentedString(sAdviseric)).append("\n");
    sb.append("    sAssemblyemail: ").append(toIndentedString(sAssemblyemail)).append("\n");
    sb.append("    sAssemblydate: ").append(toIndentedString(sAssemblydate)).append("\n");
    sb.append("    sDateofadditive: ").append(toIndentedString(sDateofadditive)).append("\n");
    sb.append("    sNotax: ").append(toIndentedString(sNotax)).append("\n");
    sb.append("    sIban: ").append(toIndentedString(sIban)).append("\n");
    sb.append("    sBic: ").append(toIndentedString(sBic)).append("\n");
    sb.append("    sMossrefnumber: ").append(toIndentedString(sMossrefnumber)).append("\n");
    sb.append("    sMossaccountname: ").append(toIndentedString(sMossaccountname)).append("\n");
    sb.append("    sKhdphAppealrefnumber: ").append(toIndentedString(sKhdphAppealrefnumber)).append("\n");
    sb.append("    sKhdphAppealreply: ").append(toIndentedString(sKhdphAppealreply)).append("\n");
    sb.append("    sKhdphCorrectiondate: ").append(toIndentedString(sKhdphCorrectiondate)).append("\n");
    sb.append("    sKhdphType: ").append(toIndentedString(sKhdphType)).append("\n");
    sb.append("    sDataboxid: ").append(toIndentedString(sDataboxid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

